///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.cpp
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/sensor.h"
 
namespace sensor
{
namespace service
{
namespace skeleton
{
 
SensorSkeletonImpl::SensorSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SensorSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<SensorSkeleton::CalculationOutput> SensorSkeletonImpl::Calculation(const float& factor, const float& offset)
{
    m_logger.LogVerbose() << "Sensor::Calculation::Requested";
    
    CalculationOutput response;
    ara::core::Promise<CalculationOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace service
} /// namespace sensor

namespace sensor
{
namespace aa
{
namespace port
{
 
Sensor::Sensor()
    : m_logger(ara::log::CreateLogger("SENS", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_SensorDataData{0.0f}
{
}
 
Sensor::~Sensor()
{
}
 
void Sensor::Start()
{
    m_logger.LogVerbose() << "Sensor::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Sensor/AA/Sensor"};
    m_interface = std::make_unique<sensor::service::skeleton::SensorSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "Sensor::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "Sensor::Start::OfferService::" << offer.Error().Message();
    }
}
 
void Sensor::Terminate()
{
    m_logger.LogVerbose() << "Sensor::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "Sensor::Terminate::StopOfferService";
}
 
void Sensor::WriteDataSensorData(const sensor::service::skeleton::events::SensorData::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_SensorDataData = data;
}
 
void Sensor::SendEventSensorDataCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->SensorData.Send(m_SensorDataData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "Sensor::SendEventSensorDataCyclic::Send" << m_SensorDataData;
            }
            else
            {
                m_logger.LogError() << "Sensor::SendEventSensorDataCyclic::Send::" << send.Error().Message();
            }
        }
        
        WriteDataSensorData(m_SensorDataData + 1.0f);
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void Sensor::SendEventSensorDataTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->SensorData.Send(m_SensorDataData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "Sensor::SendEventSensorDataTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "Sensor::SendEventSensorDataTriggered::Send::" << send.Error().Message();
    }
}
 
void Sensor::SendEventSensorDataTriggered(const sensor::service::skeleton::events::SensorData::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_SensorDataData = data;
    auto send = m_interface->SensorData.Send(m_SensorDataData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "Sensor::SendEventSensorDataTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "Sensor::SendEventSensorDataTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensor
 
/// EOF