///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rport0.h
/// SOFTWARE COMPONENT NAME           : RPort0
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_CLIENTSENSOR_AA_RPORT0_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_CLIENTSENSOR_AA_RPORT0_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorCam/sensor_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace clientsensor
{
namespace aa
{
namespace port
{
 
class RPort0
{
public:
    /// @brief Constructor
    RPort0();
    
    /// @brief Destructor
    ~RPort0();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, imageDataEvent
    void SubscribeimageDataEvent();
     
    /// @brief Stop event subscription, imageDataEvent
    void StopSubscribeimageDataEvent();
     
    /// @brief Event receive handler, imageDataEvent
    void ReceiveEventimageDataEventTriggered();
     
    /// @brief Event receive handler, imageDataEvent
    void ReceiveEventimageDataEventCyclic();
     
    /// @brief Read event data, imageDataEvent
    void ReadDataimageDataEvent(ara::com::SamplePtr<sensorCam::proxy::events::imageDataEvent::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlerimageDataEvent(std::function<void(const sensorCam::proxy::events::imageDataEvent::SampleType&)> handler);

    /// @brief Request with Response method using by software component, requestData
    void RequestrequestData(const bool& isRequest);
     
    /// @brief Regist callback from software component
    void RegistResponseHandlerrequestData(std::function<void(const sensorCam::proxy::methods::requestData::Output&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<sensorCam::proxy::SensorProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, imageDataEvent
    void RegistReceiverimageDataEvent();

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<sensorCam::proxy::SensorProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Callback from software component, imageDataEvent
    std::function<void(const sensorCam::proxy::events::imageDataEvent::SampleType&)> m_receiverimageDataEvent;

    /// @brief Callback from software component, requestData
    std::function<void(const sensorCam::proxy::methods::requestData::Output&)> m_responderrequestData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace clientsensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_CLIENTSENSOR_AA_RPORT0_H