///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.cpp
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2025-11-22 09:36:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/rootswcomponent/providersensor.h"
 
namespace providersensor
{
namespace rootswcomponent
{
 
ProviderSensor::ProviderSensor()
    : m_logger(ara::log::CreateLogger("PVSENSR", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(1)
{
}
 
ProviderSensor::~ProviderSensor()
{
}
 
bool ProviderSensor::Initialize()
{
    m_logger.LogVerbose() << "ProviderSensor::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<providersensor::rootswcomponent::port::Sensor>();
    
    // Initialize example sensor data
    m_logger.LogInfo() << "Initializing example sensor data...";
    
    // Create a vector with example data (1024 bytes)
    m_sensorData.clear();
    m_sensorData.reserve(1024);
    
    // Fill with pattern: [0, 1, 2, ..., 255, 0, 1, 2, ...]
    for (size_t i = 0; i < 1024; ++i) {
        m_sensorData.push_back(static_cast<std::uint8_t>(i % 256 + 2));
    }
    
    m_logger.LogInfo() << "Sensor data initialized with " << m_sensorData.size() << " bytes";
    
    return init;
}
 
void ProviderSensor::Start()
{
    m_logger.LogVerbose() << "ProviderSensor::Start";
    
    m_Sensor->Start();
}
 
void ProviderSensor::Terminate()
{
    m_logger.LogVerbose() << "ProviderSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_Sensor->Terminate();
}
 
void ProviderSensor::Run()
{
    m_logger.LogVerbose() << "ProviderSensor::Run";
    
    // start running
    m_running = true;
    
    // Write the example data to the sensor port buffer
    m_Sensor->WriteDataEvent_transferData(m_sensorData);
    m_logger.LogInfo() << "Example sensor data written to buffer, starting cyclic transmission...";
    
    // Start cyclic sending (sends data every 1 second)
    m_workers.Async([this] { m_Sensor->SendEventEvent_transferDataCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace rootswcomponent
} /// namespace providersensor
