///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport0.h
/// SOFTWARE COMPONENT NAME           : PPort0
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_PROVIDERSENSOR_AA_PPORT0_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_PROVIDERSENSOR_AA_PPORT0_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorCam/sensor_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace sensorCam
{
namespace skeleton
{
 
class SensorSkeletonImpl : public SensorSkeleton
{
public:
    /// @brief Constructor
    SensorSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    /// @brief Request with Response method, requestData
    ara::core::Future<SensorSkeleton::requestDataOutput> requestData(const bool& isRequest) override;

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace sensorCam

namespace providersensor
{
namespace aa
{
namespace port
{
 
class PPort0
{
public:
    /// @brief Constructor
    PPort0();
    
    /// @brief Destructor
    ~PPort0();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, imageDataEvent
    void WriteDataimageDataEvent(const sensorCam::skeleton::events::imageDataEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, imageDataEvent
    void SendEventimageDataEventCyclic();
     
    /// @brief Send event directly from buffer data, imageDataEvent
    void SendEventimageDataEventTriggered();
     
    /// @brief Send event directly with argument, imageDataEvent
    void SendEventimageDataEventTriggered(const sensorCam::skeleton::events::imageDataEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<sensorCam::skeleton::SensorSkeletonImpl> m_interface;
    
    /// @brief Data for event, imageDataEvent
    sensorCam::skeleton::events::imageDataEvent::SampleType m_imageDataEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace providersensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_PROVIDERSENSOR_AA_PPORT0_H