///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.cpp
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/rootswcomponent/port/sensor.h"
 
namespace clientsensor
{
namespace rootswcomponent
{
namespace port
{
 
Sensor::Sensor()
    : m_logger(ara::log::CreateLogger("CLSENSR", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_receiverEvent_transferData{nullptr}
{
}
 
Sensor::~Sensor()
{
}
 
void Sensor::Start()
{
    m_logger.LogVerbose() << "Sensor::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"ClientSensor/RootSwComponent/Sensor"};
    auto handler = [this](ara::com::ServiceHandleContainer<sensor::transfer::proxy::transferDataProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = sensor::transfer::proxy::transferDataProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "Sensor::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "Sensor::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void Sensor::Terminate()
{
    m_logger.LogVerbose() << "Sensor::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeEvent_transferData();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "Sensor::Terminate::StopFindService";
    }
}
 
void Sensor::Find(ara::com::ServiceHandleContainer<sensor::transfer::proxy::transferDataProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "Sensor::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "Sensor::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "Sensor::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "Sensor::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<sensor::transfer::proxy::transferDataProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeEvent_transferData();
    }
}
 
void Sensor::SubscribeEvent_transferData()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // RegistReceiverEvent_transferData();
        
        // request subscribe
        auto subscribe = m_interface->Event_transferData.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "Sensor::SubscribeEvent_transferData::Subscribed";
        }
        else
        {
            m_logger.LogError() << "Sensor::SubscribeEvent_transferData::" << subscribe.Error().Message();
        }
    }
}
 
void Sensor::StopSubscribeEvent_transferData()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->Event_transferData.Unsubscribe();
        m_logger.LogVerbose() << "Sensor::StopSubscribeEvent_transferData::Unsubscribed";
    }
}
 
void Sensor::RegistReceiverEvent_transferData()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventEvent_transferDataTriggered();
        };
        
        // regist callback
        auto callback = m_interface->Event_transferData.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "Sensor::RegistReceiverEvent_transferData::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "Sensor::RegistReceiverEvent_transferData::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void Sensor::ReceiveEventEvent_transferDataTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->Event_transferData.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->Event_transferData.GetNewSamples([&](auto samplePtr) {
                Sensor::ReadDataEvent_transferData(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "Sensor::ReceiveEventEvent_transferData::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "Sensor::ReceiveEventEvent_transferData::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void Sensor::ReceiveEventEvent_transferDataCyclic()
{
    while (m_running)
    {
        if (m_found)
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            if (m_interface->Event_transferData.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->Event_transferData.GetNewSamples([&](auto samplePtr) {
                    Sensor::ReadDataEvent_transferData(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "Sensor::ReceiveEventEvent_transferData::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "Sensor::ReceiveEventEvent_transferData::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void Sensor::ReadDataEvent_transferData(ara::com::SamplePtr<sensor::transfer::proxy::events::Event_transferData::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    if (m_receiverEvent_transferData)
    {
        m_receiverEvent_transferData(data);
    }
}
 
void Sensor::RegistEventHandlerEvent_transferData(std::function<void(const sensor::transfer::proxy::events::Event_transferData::SampleType&)> handler)
{
    m_receiverEvent_transferData = handler;
}
 
} /// namespace port
} /// namespace rootswcomponent
} /// namespace clientsensor
 
/// EOF