/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: impl_type_imagedata.idl
  Source: impl_type_imagedata.hpp
  Cyclone DDS: v0.10.4

*****************************************************************/
#ifndef DDSCXX_IMPL_TYPE_IMAGEDATA_HPP
#define DDSCXX_IMPL_TYPE_IMAGEDATA_HPP

#include <cstdint>
#include <vector>

namespace dds
{
typedef std::vector<int8_t> imageData;

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

}
}


namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write__dds_imageData(T& streamer, const ::dds::imageData& instance) {
  (void)instance;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
  return true;
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read__dds_imageData(T& streamer, ::dds::imageData& instance) {
  (void)instance;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.size());
      if (!read(streamer, se_1))
        return false;
      instance.resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
  return true;
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move__dds_imageData(T& streamer, const ::dds::imageData& instance) {
  (void)instance;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, int8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
  return true;
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max__dds_imageData(T& streamer, const ::dds::imageData& instance) {
  (void)instance;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, int8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
  return true;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_IMPL_TYPE_IMAGEDATA_HPP
