///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.h
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_FUSION_AA_SENSOR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_FUSION_AA_SENSOR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/service/sensor_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace fusion
{
namespace aa
{
namespace port
{
 
class Sensor
{
public:
    /// @brief Constructor
    Sensor();
    
    /// @brief Destructor
    ~Sensor();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, SensorData
    void SubscribeSensorData();
     
    /// @brief Stop event subscription, SensorData
    void StopSubscribeSensorData();
     
    /// @brief Event receive handler, SensorData
    void ReceiveEventSensorDataTriggered();
     
    /// @brief Event receive handler, SensorData
    void ReceiveEventSensorDataCyclic();
     
    /// @brief Read event data, SensorData
    void ReadDataSensorData(ara::com::SamplePtr<sensor::service::proxy::events::SensorData::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlerSensorData(std::function<void(const sensor::service::proxy::events::SensorData::SampleType&)> handler);

    /// @brief Request with Response method using by software component, Calculation
    void RequestCalculation(const float& factor, const float& offset);
     
    /// @brief Regist callback from software component
    void RegistResponseHandlerCalculation(std::function<void(const sensor::service::proxy::methods::Calculation::Output&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<sensor::service::proxy::SensorProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, SensorData
    void RegistReceiverSensorData();

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<sensor::service::proxy::SensorProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Callback from software component, SensorData
    std::function<void(const sensor::service::proxy::events::SensorData::SampleType&)> m_receiverSensorData;

    /// @brief Callback from software component, Calculation
    std::function<void(const sensor::service::proxy::methods::Calculation::Output&)> m_responderCalculation;
};
 
} /// namespace port
} /// namespace aa
} /// namespace fusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_FUSION_AA_SENSOR_H