///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : clientsensor.cpp
/// SOFTWARE COMPONENT NAME           : ClientSensor
/// GENERATED DATE                    : 2025-11-22 09:36:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/rootswcomponent/clientsensor.h"
#include <opencv2/opencv.hpp>
 
namespace clientsensor
{
namespace rootswcomponent
{
 
ClientSensor::ClientSensor()
    : m_logger(ara::log::CreateLogger("CLSENSR", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(1)
{
}
 
ClientSensor::~ClientSensor()
{
}
 
bool ClientSensor::Initialize()
{
    m_logger.LogVerbose() << "ClientSensor::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<clientsensor::rootswcomponent::port::Sensor>();
    
    // put your code for initialization

    m_Sensor->RegistEventHandlerEvent_transferData([this](const std::vector<std::uint8_t>& data) {
        if (data.empty()) return;

        m_logger.LogInfo() << "Received data size: " << data.size();

        try {
            // 1. Decode byte data to OpenCV image
            cv::Mat img = cv::imdecode(data, cv::IMREAD_COLOR);

            if (!img.empty()) {
                // 2. Write image to file
                std::string filename = "received_output.jpg";
                if (cv::imwrite(filename, img)) {
                    m_logger.LogInfo() << "Image saved to " << filename.c_str();
                } else {
                    m_logger.LogError() << "Failed to save image file";
                }
            } else {
                m_logger.LogError() << "Failed to decode image";
            }
        } catch (const cv::Exception& e) {
            m_logger.LogError() << "OpenCV Exception: " << e.what();
        }
    });
    
    return init;
}
 
void ClientSensor::Start()
{
    m_logger.LogVerbose() << "ClientSensor::Start";
    
    m_Sensor->Start();
}
 
void ClientSensor::Terminate()
{
    m_logger.LogVerbose() << "ClientSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_Sensor->Terminate();
}
 
void ClientSensor::Run()
{
    m_logger.LogVerbose() << "ClientSensor::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_Sensor->ReceiveEventEvent_transferDataCyclic(); });
    
    // m_workers.Wait();
    // This line code to keep the Run callback function active
    while (m_running)
    {
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
} /// namespace rootswcomponent
} /// namespace clientsensor
