///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.cpp
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/rootswcomponent/providersensor.h"
#include <opencv2/opencv.hpp>
 
namespace providersensor
{
namespace rootswcomponent
{
 
ProviderSensor::ProviderSensor()
    : m_logger(ara::log::CreateLogger("PVSENSR", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
{
}
 
ProviderSensor::~ProviderSensor()
{
}
 
bool ProviderSensor::Initialize()
{
    m_logger.LogVerbose() << "ProviderSensor::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<providersensor::rootswcomponent::port::Sensor>();
    m_Sensorv2 = std::make_unique<providersensor::rootswcomponent::port::Sensorv2>();
    
    // put your code for initialization
    
    return init;
}
 
void ProviderSensor::Start()
{
    m_logger.LogVerbose() << "ProviderSensor::Start";
    
    // m_Sensor->Start();  // Disabled normal sensor
    m_Sensorv2->Start();
}
 
void ProviderSensor::Terminate()
{
    m_logger.LogVerbose() << "ProviderSensor::Terminate";
    
    // stop running
    m_running = false;
    
    // m_Sensor->Terminate();  // Disabled normal sensor
    m_Sensorv2->Terminate();
}
 
void ProviderSensor::Run()
{
    m_logger.LogVerbose() << "ProviderSensor::Run";
    
    // start running
    m_running = true;
    
    // // Read the image from file
    // m_workers.Async([this] { m_Sensor->SendEventEvent_transferDataCyclic(); });  // Disabled normal sensor
    // m_workers.Async([this] { m_Sensorv2->SendEventEvent_RequestDataCyclic(); });

    // m_workers.Async(
    //     [this] {
    //         ara::sensor::SensorVectorType m_sensorData; 
    //         while (m_running) {
    //             cv::Mat img = cv::imread("yellowLights.jpg", cv::IMREAD_COLOR);

    //             if (img.empty()) {
    //                 m_logger.LogError() << "Failed to load image! Using dummy data.";
    //                 // Fallback: use dummy data
    //                 m_sensorData.assign(2000, 0);
    //                 m_logger.LogInfo() << "Image encoded successfully. Size: " << m_sensorData.size();
    //             }

    //             else {
    //                 std::vector<uchar> buf;
    //                 cv::imencode(".jpg", img, buf);
    //                 m_sensorData.assign(buf.begin(), buf.end());
    //                 m_logger.LogInfo() << "Image encoded successfully. Size: " << m_sensorData.size();
    //             }

    //             m_Sensorv2->SendEventEvent_RequestDataTriggered(m_sensorData);
    //             m_sensorData.clear();
    //             std::this_thread::sleep_for(std::chrono::seconds(1)); // Adjust the sleep duration as needed
    //         }
    //     }
    // );


    // New camera capture and transmission loop
    m_workers.Async(
        [this] {
            // 1. INITIALIZE CAMERA
            // Open the default camera (index 0 usually refers to /dev/video0)
            cv::VideoCapture cap(0); 
            
            // Set resolution (Optional but recommended to optimize bandwidth)
            // Lower resolution reduces latency over DDS/SOMEIP
            cap.set(cv::CAP_PROP_FRAME_WIDTH, 640);
            cap.set(cv::CAP_PROP_FRAME_HEIGHT, 640);

            if (!cap.isOpened()) {
                m_logger.LogError() << "ERROR: Could not open camera!";
                // You might want to handle this error (e.g., fallback to dummy data)
            } else {
                m_logger.LogInfo() << "Camera opened successfully";
            }

            ara::sensor::SensorVectorType m_sensorData; 
            cv::Mat frame;

            // Main application loop
            while (m_running) {
                // 2. CAPTURE FRAME
                bool ret = cap.read(frame); // Grab the next frame

                if (!ret || frame.empty()) {
                    m_logger.LogError() << "Failed to grab frame from camera! Sending dummy data...";
                    
                    // Fallback: Populate with dummy data to prevent system hang
                    m_sensorData.assign(2000, 0); 
                }
                else {
                    // (Optional) Resize logic if specific output size is needed
                    // cv::resize(frame, frame, cv::Size(320, 240));

                    // 3. ENCODE IMAGE (Compression)
                    std::vector<uchar> buf;
                    
                    // Compress to JPEG with 100% quality to reduce payload size
                    std::vector<int> params = {cv::IMWRITE_JPEG_QUALITY, 100};
                    cv::imencode(".jpg", frame, buf, params);
                    
                    // Copy the compressed data into the AUTOSAR vector
                    m_sensorData.assign(buf.begin(), buf.end());
                    
                    m_logger.LogInfo() << "Camera frame encoded. Size: " << m_sensorData.size() << " bytes";
                }

                // 4. TRANSMIT DATA
                // Send the data via the Triggered event method
                m_Sensorv2->SendEventEvent_RequestDataTriggered(m_sensorData);
                
                // Clear the vector for the next iteration
                m_sensorData.clear();
                
                // 5. CONTROL FRAME RATE
                // Sleep for approx. 25ms to achieve ~40 FPS. Increase this value to lower the FPS.
                std::this_thread::sleep_for(std::chrono::milliseconds(25)); 
            }
            
            // Release camera resources when the application stops
            cap.release();
        }
    );
    
    m_workers.Wait();
}
 
} /// namespace rootswcomponent
} /// namespace providersensor
