///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : transferdata_v2_skeleton.h
/// SERVICE INTERFACE NAME            : transferData_v2
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_SENSOR_TRANSV2_SERVICE_INTERFACE_TRANSFERDATA_V2_SKELETON_H
#define PARA_COM_GEN_SENSOR_TRANSV2_SERVICE_INTERFACE_TRANSFERDATA_V2_SKELETON_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_01004}
#include "transferdata_v2_common.h"
#include "para/com/skeleton/skeleton_interface.h"
/// @uptrace{SWS_CM_01005}
namespace sensor
{
namespace transv2
{
/// @uptrace{SWS_CM_01006}
namespace skeleton
{
class transferData_v2Skeleton;
/// @uptrace{SWS_CM_01009}
namespace events
{
/// @uptrace{SWS_CM_00003}
class Event_RequestData
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = ara::sensor::SensorVectorType;
    /// @brief Constructor
    explicit Event_RequestData(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::sensor::transv2::SensorVectorTypeEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~Event_RequestData() = default;
    /// @brief Delete copy constructor
    Event_RequestData(const Event_RequestData& other) = delete;
    /// @brief Delete copy assignment
    Event_RequestData& operator=(const Event_RequestData& other) = delete;
    /// @brief Move constructor
    Event_RequestData(Event_RequestData&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    Event_RequestData& operator=(Event_RequestData&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::sensor::transv2::SensorVectorTypeEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = ara::sensor::SensorVectorType_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::sensor::transv2::SensorVectorTypeEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"Event_RequestData"};
};
} /// namespace events
/// @uptrace{SWS_CM_01031}
namespace fields
{
} /// namespace fields
/// @uptrace{SWS_CM_00002}
class transferData_v2Skeleton
{
public:
    /// @uptrace{SWS_CM_00191}
    struct RequestDataOutput
    {
        ara::sensor::SensorVectorType outputVector;
    };
    /// @brief Constructor
    /// @uptrace{SWS_CM_00002, SWS_CM_00152}
    transferData_v2Skeleton(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : mInterface(std::make_unique<para::com::SkeletonInterface>(instanceSpec, mode))
        , mDdsInterface(std::make_unique<para::com::SkeletonDdsInterface>(instanceSpec, mode))
        , mProtocol(para::com::GetServiceProtocol(instanceSpec))
        , Event_RequestData(mInterface.get(), mDdsInterface.get(), mProtocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::sensor::transv2::transferData_v2Method_Request, dds::sensor::transv2::transferData_v2Method_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~transferData_v2Skeleton() = default;
    /// @brief Delete copy constructor
    /// @uptrace{SWS_CM_00134}
    transferData_v2Skeleton(const transferData_v2Skeleton& other) = delete;
    /// @brief Delete copy assignment
    /// @uptrace{SWS_CM_00134}
    transferData_v2Skeleton& operator=(const transferData_v2Skeleton& other) = delete;
    /// @brief Move constructor
    /// @uptrace{SWS_CM_00135}
    transferData_v2Skeleton(transferData_v2Skeleton&& other) noexcept
        : mInterface(std::move(other.mInterface))
        , mDdsInterface(std::move(other.mDdsInterface))
        , mProtocol(std::move(other.mProtocol))
        , Event_RequestData(std::move(other.Event_RequestData))
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::sensor::transv2::transferData_v2Method_Request, dds::sensor::transv2::transferData_v2Method_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
    }
    /// @brief Move assignment
    /// @uptrace{SWS_CM_00135}
    transferData_v2Skeleton& operator=(transferData_v2Skeleton&& other) noexcept
    {
        mInterface = std::move(other.mInterface);
        mDdsInterface = std::move(other.mDdsInterface);
        mProtocol = std::move(other.mProtocol);
        Event_RequestData = std::move(other.Event_RequestData);
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kRequestDataCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    HandleRequestData(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::sensor::transv2::transferData_v2Method_Request, dds::sensor::transv2::transferData_v2Method_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
        return *this;
    }
    /// @brief Send "OfferService" message to Communication Management
    /// @uptrace{SWS_CM_00101}
    ara::core::Result<void> OfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->OfferService();
            }
            case para::com::ServiceProtocol::kIpc :
            {
            	return mInterface->OfferService();
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            	return mDdsInterface->OfferService();
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Send "StopOfferService" message to Communication Management
    /// @uptrace{SWS_CM_00111}
    void StopOfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopOfferService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopOfferService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopOfferService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Allows the implementation providing the service method to trigger the execution of the next service consumer method call at a specific point of time
    ///        if the processing mode is set to kPoll.
    /// @note This function requires that ara::com::MethodCallProcessingMode is configured as kPoll by constructor
    /// @uptrace{SWS_CM_00199}
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        ara::core::Promise<bool> promise{};
        ara::core::Result<bool> ret{false};
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                ret = mDdsInterface->ProcessNextMethodCall();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        if (ret.HasValue())
        {
            promise.set_value(ret.Value());
        }
        else
        {
            promise.SetError(ret.Error());
        }
        return promise.get_future();
    }
    /// @brief In case the call to E2E_check indicated a failed E2E check of the request message, the server application can get notified via an E2E error handler.
    /// @uptrace{SWS_CM_10470}
    virtual void E2EErrorHandler(const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter)
    {
    }
    
private:
    std::unique_ptr<para::com::SkeletonInterface> mInterface;
    std::unique_ptr<para::com::SkeletonDdsInterface> mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    
public:
    /// @brief Event, Event_RequestData
    events::Event_RequestData Event_RequestData;
    /// @brief Method, RequestData
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<RequestDataOutput> RequestData(const bool& isRequest) = 0;
    
private:
    void HandleRequestData(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        bool _isRequest_;
        deserializer.read(props, _isRequest_);
        auto future = RequestData(_isRequest_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            RequestDataOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.outputVector);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kRequestDataCallSign, retResult, retData, token);
    }
    #ifdef PARA_DDS_IMPLEMENTATION
    void HandleDdsMethod(const dds::sub::AnyDataReader& reader)
    {
        dds::sub::DataReader<dds::sensor::transv2::transferData_v2Method_Request> _reader_ = reader;
        dds::sub::LoanedSamples<dds::sensor::transv2::transferData_v2Method_Request> _requests_;
        _requests_ = _reader_.take();
        for (auto& _request_ : _requests_)
        {
            if (_request_->info().valid())
            {
                auto _data_ = _request_.data().data();
                switch (_data_._d())
                {
                    case dds::sensor::transv2::transferData_v2Method_RequestData_Hash :
                    {
                        HandleRequestData(_data_.RequestData(), _request_.data().header());
                        break;
                    }
                    default : break;
                }
            }
        }
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void HandleRequestData(const dds::sensor::transv2::transferData_v2Method_RequestData_In& data, const dds::rpc::RequestHeader token)
    {
        dds::sensor::transv2::transferData_v2Method_RequestData_Result _result_{};
        bool _isRequest = data.isRequest();
        auto future = this->RequestData(_isRequest);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::sensor::transv2::transferData_v2Method_RequestData_Out _out_args_;
            _out_args_.outputVector() = ara::sensor::SensorVectorType_ConvertToDdsType(result.Value().outputVector);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::sensor::transv2::transferData_v2Method_Return _return_;
        _return_.RequestData(_result_, dds::sensor::transv2::transferData_v2Method_RequestData_Hash);
        dds::sensor::transv2::transferData_v2Method_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::sensor::transv2::transferData_v2Method_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    const std::string kRequestDataCallSign{"RequestData"};
};
} /// namespace skeleton
} /// namespace transv2
} /// namespace sensor
#endif /// PARA_COM_GEN_SENSOR_TRANSV2_SERVICE_INTERFACE_TRANSFERDATA_V2_SKELETON_H