///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : clientsensor.cpp
/// SOFTWARE COMPONENT NAME           : ClientSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/aa/clientsensor.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <iostream>

namespace clientsensor
{
namespace aa
{

ClientSensor::ClientSensor()
    : m_logger(ara::log::CreateLogger("cSen", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
{
}

ClientSensor::~ClientSensor()
{
}

bool ClientSensor::Initialize()
{
    m_logger.LogVerbose() << "ClientSensor::Initialize";
    
    // Tạo Cấu trúc tĩnh trong hàm để giữ Connection
    static int sock = -1;
    static struct sockaddr_in server_addr;

    // Hàm Lambda tự động gọi nếu Socket mất kết nối
    auto ConnectTCP = [&]() {
        if (sock >= 0) close(sock);
        sock = socket(AF_INET, SOCK_STREAM, 0);
        if (sock < 0) return;
        
        server_addr.sin_family = AF_INET;
        server_addr.sin_port = htons(8888);
        server_addr.sin_addr.s_addr = inet_addr("127.0.0.1");

        // Cố gắng kết nối vào Python script (Nếu Python chưa chạy thì bỏ qua, hình frame bị drop)
        if (connect(sock, (struct sockaddr*)&server_addr, sizeof(server_addr)) < 0) {
            close(sock);
            sock = -1;
        }
    };

    // Gọi lần đầu lúc khởi động ứng dụng
    ConnectTCP();

    bool init = true;
    m_RPort0 = std::make_unique<clientsensor::aa::port::RPort0>();
    
    m_RPort0->RegistEventHandlerimageDataEvent([ConnectTCP, this](const sensorCam::proxy::events::imageDataEvent::SampleType& data) {
        if (data.empty()) return;

        // Nếu TCP bị đứt hoặc chưa khởi động Python, cố connect lại ngay trước khi ném dữ liệu
        if (sock < 0) {
            ConnectTCP();
        }

        if (sock >= 0) {
            // Bước 1: Gửi chiều dài Frame là 4 Bytes số nguyên (uint32_t)
            uint32_t len = data.size();
            ssize_t n1 = send(sock, &len, sizeof(uint32_t), MSG_NOSIGNAL);
            
            // Bước 2: Gửi ruột tấm hình
            ssize_t n2 = -1;
            if (n1 == sizeof(uint32_t)) {
                n2 = send(sock, data.data(), len, MSG_NOSIGNAL);
            }
            
            // Nếu phát hiện kết nối bị đóng sập bởi Python (Broken Pipe), đánh dấu sock = -1
            if (n1 < 0 || n2 < 0) {
                close(sock);
                sock = -1;
            }
        }
    });
    
    return init;
}
 
void ClientSensor::Start()
{
    m_logger.LogVerbose() << "ClientSensor::Start";
    
    m_RPort0->Start();
}
 
void ClientSensor::Terminate()
{
    m_logger.LogVerbose() << "ClientSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_RPort0->Terminate();
}
 
void ClientSensor::Run()
{
    m_logger.LogVerbose() << "ClientSensor::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_RPort0->ReceiveEventimageDataEventCyclic(); });
    
    // m_workers.Wait();

    while (m_running)
    {
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
} /// namespace aa
} /// namespace clientsensor
