///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : actuator.cpp
/// SOFTWARE COMPONENT NAME           : Actuator
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "actuator/aa/actuator.h"
 
namespace actuator
{
namespace aa
{
 
Actuator::Actuator()
    : m_logger(ara::log::CreateLogger("ACTU", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(1)
{
}
 
Actuator::~Actuator()
{
}
 
bool Actuator::Initialize()
{
    m_logger.LogVerbose() << "Actuator::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<actuator::aa::port::Sensor>();
    
    // put your code for initialization

    m_Sensor->RegistEventHandlerSensorData(
        [this](const sensor::service::proxy::events::SensorData::SampleType& data)
        {
            m_logger.LogVerbose() << "[Actuator] SensorData via callback = " << data;
        });
    
    return init;
}
 
void Actuator::Start()
{
    m_logger.LogVerbose() << "Actuator::Start";
    
    m_Sensor->Start();
}
 
void Actuator::Terminate()
{
    m_logger.LogVerbose() << "Actuator::Terminate";
    
    // stop running
    m_running = false;
    
    m_Sensor->Terminate();
}
 
void Actuator::Run()
{
    m_logger.LogVerbose() << "Actuator::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_Sensor->ReceiveEventSensorDataCyclic(); });
    
    // m_workers.Wait();

    // keep alive
    while (m_running) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}
 
} /// namespace aa
} /// namespace actuator
