///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.cpp
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/aa/providersensor.h"
 
namespace providersensor
{
namespace aa
{

// Class names for traffic light detection
const char* ProviderSensor::CLASS_NAMES[] = {
    "Green", "Red", "Yellow"
};

const int ProviderSensor::CLASS_NAMES_SIZE = sizeof(CLASS_NAMES) / sizeof(CLASS_NAMES[0]);

// IoU calculation
float ProviderSensor::IoU(const cv::Rect& a, const cv::Rect& b) {
    int x1 = std::max(a.x, b.x);
    int y1 = std::max(a.y, b.y);
    int x2 = std::min(a.x + a.width, b.x + b.width);
    int y2 = std::min(a.y + a.height, b.y + b.height);
    int w = std::max(0, x2 - x1);
    int h = std::max(0, y2 - y1);
    float inter = float(w) * float(h);
    float uni = float(a.area() + b.area()) - inter;
    return uni > 0 ? inter / uni : 0.0f;
}

// Non-Maximum Suppression
std::vector<Det> ProviderSensor::nms(const std::vector<Det>& dets, float iou_thr) {
    if (dets.empty()) return {};
    std::vector<int> idx(dets.size());
    std::iota(idx.begin(), idx.end(), 0);
    std::sort(idx.begin(), idx.end(),
              [&](int a, int b) { return dets[a].score > dets[b].score; });

    std::vector<Det> keep;
    std::vector<char> suppressed(dets.size(), 0);
    for (size_t _i = 0; _i < idx.size(); ++_i) {
        int i = idx[_i];
        if (suppressed[i]) continue;
        keep.push_back(dets[i]);
        for (size_t _j = _i + 1; _j < idx.size(); ++_j) {
            int j = idx[_j];
            if (suppressed[j]) continue;
            if (dets[i].cls == dets[j].cls &&
                IoU(dets[i].rect, dets[j].rect) > iou_thr) {
                suppressed[j] = 1;
            }
        }
    }
    return keep;
}
 
ProviderSensor::ProviderSensor()
    : m_logger(ara::log::CreateLogger("pSen", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
    , m_inputHeight(0)
    , m_inputWidth(0)
    , m_inputChannels(0)
    , m_numClasses(0)
    , m_numDetections(0)
{
}
 
ProviderSensor::~ProviderSensor()
{
}

bool ProviderSensor::InitializeTFLite()
{
    m_logger.LogInfo() << "Initializing TFLite (3 Classes, NMS=True)...";
    
    m_model = tflite::FlatBufferModel::BuildFromFile("yolo_26_tflite/best_float16_yolo26.tflite");
    
    if (!m_model) {
        m_logger.LogError() << "Failed to load TFLite model!";
        return false;
    }
    
    tflite::ops::builtin::BuiltinOpResolver resolver;
    if (tflite::InterpreterBuilder(*m_model, resolver)(&m_interpreter) != kTfLiteOk || !m_interpreter) {
        m_logger.LogError() << "Failed to build TFLite interpreter!";
        return false;
    }
    
    m_interpreter->SetNumThreads(4);
    
    if (m_interpreter->AllocateTensors() != kTfLiteOk) {
        m_logger.LogError() << "Failed to allocate tensors!";
        return false;
    }
    
    // INPUT SETUP
    int in_idx = m_interpreter->inputs()[0];
    TfLiteTensor* in_t = m_interpreter->tensor(in_idx);
    
    m_inputHeight = in_t->dims->data[1];
    m_inputWidth = in_t->dims->data[2];
    m_inputChannels = in_t->dims->data[3];
    
    m_logger.LogInfo() << "Input: [1, " << m_inputHeight << ", " << m_inputWidth << ", " << m_inputChannels << "]";
    
    // OUTPUT SETUP [1, 300, 6]
    const auto& outs = m_interpreter->outputs();
    int out_idx = outs[0];
    const TfLiteTensor* ot = m_interpreter->tensor(out_idx);

    // Validate Shape
    int d0 = ot->dims->data[0]; // 1
    int d1 = ot->dims->data[1]; // 300 (Num Detections)
    int d2 = (ot->dims->size > 2) ? ot->dims->data[2] : 0; // 6 (Features)

    m_logger.LogInfo() << "Output Shape: [" << d0 << ", " << d1 << ", " << d2 << "]";

    // With Model NMS=True, the last channel is ALWAYS 6 [x,y,w,h,conf,cls]
    if (d2 != 6) {
        m_logger.LogError() << "Error: Expected 6 channels [x,y,w,h,conf,cls] because NMS is True.";
        // If the model outputs 7 channels (xywh + 3 class prob), the loop logic needs to be modified
        // But your previous log showed [1, 300, 6], so we stick to 6.
    }

    m_numDetections = d1; 
    m_numClasses = CLASS_NAMES_SIZE; // Green, Red, Yellow
    
    return true;
}

std::vector<Det> ProviderSensor::ProcessFrame(const cv::Mat& frame)
{
    std::vector<Det> final_dets;
    if (frame.empty() || !m_interpreter) return final_dets;

    // --- 1. PREPROCESS: LETTERBOX ---
    // Goal: Resize while maintaining aspect ratio and add padding
    int target_w = m_inputWidth;  // 320
    int target_h = m_inputHeight; // 320
    
    float scale = std::min((float)target_w / frame.cols, (float)target_h / frame.rows);
    int new_w = (int)(frame.cols * scale);
    int new_h = (int)(frame.rows * scale);
    
    cv::Mat resized;
    cv::resize(frame, resized, cv::Size(new_w, new_h));
    
    // Create gray background image (114 is the standard YOLO color)
    cv::Mat canvas(target_h, target_w, CV_8UC3, cv::Scalar(114, 114, 114));
    
    // Calculate offset to center the image (or place at top-left)
    // Ultralytics defaults to center, but for simplicity we place at 0,0
    // If exact centering like Python is desired:
    int dw = (target_w - new_w) / 2;
    int dh = (target_h - new_h) / 2;
    
    // Copy resized image to canvas
    resized.copyTo(canvas(cv::Rect(dw, dh, new_w, new_h)));
    
    // Prepare input for model
    cv::Mat f32;
    cv::cvtColor(canvas, canvas, cv::COLOR_BGR2RGB);
    canvas.convertTo(f32, CV_32FC3, 1.0f / 255.0f);
    
    std::memcpy(m_interpreter->typed_input_tensor<float>(0), f32.data, f32.total() * f32.elemSize());

    // --- 2. INFERENCE ---
    if (m_interpreter->Invoke() != kTfLiteOk) {
        m_logger.LogError() << "Inference failed!";
        return final_dets;
    }

    // --- 3. PARSE OUTPUT ---
    int out_idx = m_interpreter->outputs()[0];
    const float* out = m_interpreter->typed_tensor<float>(out_idx);
    
    const int N = m_numDetections; 
    const int C = 6; // [x1, y1, x2, y2, score, cls]

    std::vector<Det> proposals;
    proposals.reserve(N);

    for (int i = 0; i < N; ++i) {
        const float* p = out + (i * C);
        
        float score = p[4];
        if (score < CONF_THRESHOLD) continue;
        
        int cls_id = (int)p[5];
        if (cls_id < 0 || cls_id >= 3) continue;

        // Get coordinates on 320x320 image (with padding)
        float x1 = p[0] * target_w;
        float y1 = p[1] * target_h;
        float x2 = p[2] * target_w;
        float y2 = p[3] * target_h;
        
        // --- 4. MAP COORDINATES BACK TO ORIGINAL IMAGE ---
        // Subtract padding (dw, dh)
        x1 -= dw; x2 -= dw;
        y1 -= dh; y2 -= dh;
        
        // Divide by scale factor
        x1 /= scale; x2 /= scale;
        y1 /= scale; y2 /= scale;
        
        // Clamp to original frame bounds
        x1 = std::max(0.0f, std::min(x1, (float)frame.cols - 1));
        y1 = std::max(0.0f, std::min(y1, (float)frame.rows - 1));
        x2 = std::max(0.0f, std::min(x2, (float)frame.cols - 1));
        y2 = std::max(0.0f, std::min(y2, (float)frame.rows - 1));

        int rw = int(x2 - x1);
        int rh = int(y2 - y1);
        
        if (rw > 0 && rh > 0) {
            proposals.push_back(Det{cv::Rect((int)x1, (int)y1, rw, rh), cls_id, score});
        }
    }
    
    final_dets = nms(proposals, IOU_THRESHOLD);
    return final_dets;
}
 
bool ProviderSensor::Initialize()
{
    m_logger.LogVerbose() << "ProviderSensor::Initialize";
    
    bool init = true;
    
    m_PPort0 = std::make_unique<providersensor::aa::port::PPort0>();
    
    // put your code for initialization

    // Initialize TFLite model
    if (!InitializeTFLite()) {
        m_logger.LogError() << "Failed to initialize TFLite model!";
        init = false;
    }
    
    return init;
}
 
void ProviderSensor::Start()
{
    m_logger.LogVerbose() << "ProviderSensor::Start";
    
    m_PPort0->Start();
}
 
void ProviderSensor::Terminate()
{
    m_logger.LogVerbose() << "ProviderSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_PPort0->Terminate();
}
 
void ProviderSensor::Run()
{
    m_logger.LogVerbose() << "ProviderSensor::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_PPort0->SendEventimageDataEventCyclic(); });

    m_workers.Async(
        [this] {
            // 1. INITIALIZE CAMERA
            cv::VideoCapture cap(0);
            
            // Set resolution
            cap.set(cv::CAP_PROP_FRAME_WIDTH, 320);
            cap.set(cv::CAP_PROP_FRAME_HEIGHT, 320);

            if (!cap.isOpened()) {
                m_logger.LogError() << "ERROR: Could not open camera!";
            } else {
                m_logger.LogInfo() << "Camera opened successfully";
            }

            cv::Mat frame;
            // imageData dataImageDataEvent;

            // Main application loop
            while (m_running) {
                auto t_total_start = std::chrono::high_resolution_clock::now();
                
                // 2. CAPTURE FRAME
                bool ret = cap.read(frame);

                // // Read image from file instead of camera
                // // Since we installed the image to the same bin directory as the executable,
                // // we can try to read it from the current directory.
                // frame = cv::imread("image.jpg");
                // bool ret = !frame.empty();

                if (!ret) {
                     m_logger.LogError() << "Failed to grab frame from file: image.jpg!";
                     // m_sensorData.assign(2000, 0);
                     // If we cannot read the file, maybe wait a bit and try again or just sleep
                }
                else {
                    // 3. RUN YOLO INFERENCE
                    auto t_inf_start = std::chrono::high_resolution_clock::now();
                    std::vector<Det> detections = ProcessFrame(frame);
                    auto t_inf_end = std::chrono::high_resolution_clock::now();
                    std::chrono::duration<double, std::milli> t_inf_ms = t_inf_end - t_inf_start;
                    
                    m_logger.LogInfo() << "Inference time: " << t_inf_ms.count() << " ms, Detections: " << detections.size();
                    
                    // 4. DRAW DETECTIONS ON FRAME
                    for (const auto& d : detections) {
                        cv::rectangle(frame, d.rect, cv::Scalar(0, 255, 0), 2);
                        
                        char text[128];
                        std::snprintf(text, sizeof(text), "%s %.2f",
                                      (d.cls >= 0 && d.cls < CLASS_NAMES_SIZE) ? CLASS_NAMES[d.cls] : "cls?",
                                      d.score);
                        
                        int baseline = 0;
                        cv::Size ts = cv::getTextSize(text, cv::FONT_HERSHEY_SIMPLEX, 0.6, 2, &baseline);
                        int x1 = d.rect.x;
                        int y1 = std::max(0, d.rect.y - ts.height - 6);
                        
                        cv::rectangle(frame,
                                      cv::Point(x1, y1),
                                      cv::Point(x1 + ts.width + 6, y1 + ts.height + 6),
                                      cv::Scalar(0, 255, 0), cv::FILLED);
                        cv::putText(frame, text,
                                    cv::Point(x1 + 3, y1 + ts.height + 1),
                                    cv::FONT_HERSHEY_SIMPLEX, 0.6,
                                    cv::Scalar(0, 0, 0), 2);
                        
                        // Log each detection
                        m_logger.LogInfo() << "Detected: " << CLASS_NAMES[d.cls] 
                                           << " conf=" << d.score
                                           << " box=[" << d.rect.x << "," << d.rect.y 
                                           << "," << d.rect.width << "," << d.rect.height << "]";
                    }
                    
                    // 5. ENCODE ANNOTATED IMAGE
                    std::vector<uchar> buf;
                    std::vector<int> params = {cv::IMWRITE_JPEG_QUALITY, 100};
                    cv::imencode(".jpg", frame, buf, params);

                    sensorCam::skeleton::events::imageDataEvent::SampleType autosar_buf(buf.begin(), buf.end());
                    
                    m_PPort0->WriteDataimageDataEvent(autosar_buf);
                    
                    auto t_total_end = std::chrono::high_resolution_clock::now();
                    std::chrono::duration<double, std::milli> t_total_ms = t_total_end - t_total_start;
                    
                    m_logger.LogInfo() << "Frame processed. Size: " << buf.size() 
                                       << " bytes, Total time: " << t_total_ms.count() << " ms";
                }


                // // 6. TRANSMIT DATA
                // if (!dataImageDataEvent.empty()) {
                //      m_PPort0->SendEventimageDataEventTriggered();
                // }
                
                // dataImageDataEvent.clear();

                m_PPort0->SendEventimageDataEventTriggered();
                
                // 7. CONTROL FRAME RATE (~40 FPS) -> Adjusted to 2000ms as per original logic for slow loop
                // std::this_thread::sleep_for(std::chrono::milliseconds(2000));
            }
            
            // cap.release();
        }
    );
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace providersensor
