///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : clientsensor.h
/// SOFTWARE COMPONENT NAME           : ClientSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_CLIENTSENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_CLIENTSENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/aa/port/rport0.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"

#include <opencv2/opencv.hpp>
 
namespace clientsensor
{
namespace aa
{
 
class ClientSensor
{
public:
    /// @brief Constructor
    ClientSensor();
    
    /// @brief Destructor
    ~ClientSensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {ClientSensor.RPort0}
    std::unique_ptr<clientsensor::aa::port::RPort0> m_RPort0;
};
 
} /// namespace aa
} /// namespace clientsensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_CLIENTSENSOR_AA_H