///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.h
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSOR_AA_SENSOR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSOR_AA_SENSOR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/service/sensor_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
#include <fstream>
#include <string>
 
namespace sensor
{
namespace service
{
namespace skeleton
{
 
class SensorSkeletonImpl : public SensorSkeleton
{
public:
    /// @brief Constructor
    SensorSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    /// @brief Request with Response method, Calculation
    ara::core::Future<SensorSkeleton::CalculationOutput> Calculation(const float& factor, const float& offset) override;

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace service
} /// namespace sensor

namespace sensor
{
namespace aa
{
namespace port
{
 
class Sensor
{
public:
    /// @brief Constructor
    Sensor();
    
    /// @brief Destructor
    ~Sensor();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, SensorData
    void WriteDataSensorData(const sensor::service::skeleton::events::SensorData::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, SensorData
    void SendEventSensorDataCyclic();
     
    /// @brief Send event directly from buffer data, SensorData
    void SendEventSensorDataTriggered();
     
    /// @brief Send event directly with argument, SensorData
    void SendEventSensorDataTriggered(const sensor::service::skeleton::events::SensorData::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

    /// @brief Serial
    std::ifstream m_serial;

    /// @brief line buffer
    std::string m_lineBuffer;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<sensor::service::skeleton::SensorSkeletonImpl> m_interface;
    
    /// @brief Data for event, SensorData
    sensor::service::skeleton::events::SensorData::SampleType m_SensorDataData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace sensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSOR_AA_SENSOR_H