///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.cpp
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "actuator/aa/port/sensor.h"
 
namespace actuator
{
namespace aa
{
namespace port
{
 
Sensor::Sensor()
    : m_logger(ara::log::CreateLogger("ACTU", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
    , m_receiverSensorData{nullptr}
    , m_responderCalculation{nullptr}
{
}
 
Sensor::~Sensor()
{
}
 
void Sensor::Start()
{
    m_logger.LogVerbose() << "Sensor::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"Actuator/AA/Sensor"};
    auto handler = [this](ara::com::ServiceHandleContainer<sensor::service::proxy::SensorProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = sensor::service::proxy::SensorProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "Sensor::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "Sensor::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void Sensor::Terminate()
{
    m_logger.LogVerbose() << "Sensor::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeSensorData();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "Sensor::Terminate::StopFindService";
    }
}
 
void Sensor::Find(ara::com::ServiceHandleContainer<sensor::service::proxy::SensorProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "Sensor::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "Sensor::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "Sensor::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "Sensor::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_unique<sensor::service::proxy::SensorProxy>(handles[0]);
        m_findHandle = std::make_unique<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeSensorData();
    }
}
 
void Sensor::SubscribeSensorData()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        RegistReceiverSensorData();
        
        // request subscribe
        auto subscribe = m_interface->SensorData.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "Sensor::SubscribeSensorData::Subscribed";
        }
        else
        {
            m_logger.LogError() << "Sensor::SubscribeSensorData::" << subscribe.Error().Message();
        }
    }
}
 
void Sensor::StopSubscribeSensorData()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->SensorData.Unsubscribe();
        m_logger.LogVerbose() << "Sensor::StopSubscribeSensorData::Unsubscribed";
    }
}
 
void Sensor::RegistReceiverSensorData()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventSensorDataTriggered();
        };
        
        // regist callback
        auto callback = m_interface->SensorData.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "Sensor::RegistReceiverSensorData::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "Sensor::RegistReceiverSensorData::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void Sensor::ReceiveEventSensorDataTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        
        if (m_interface->SensorData.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->SensorData.GetNewSamples([&](auto samplePtr) {
                Sensor::ReadDataSensorData(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "Sensor::ReceiveEventSensorData::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "Sensor::ReceiveEventSensorData::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void Sensor::ReceiveEventSensorDataCyclic()
{
    while (m_running)
    {
        if (m_found)
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            if (m_interface->SensorData.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->SensorData.GetNewSamples([&](auto samplePtr) {
                    Sensor::ReadDataSensorData(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "Sensor::ReceiveEventSensorData::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "Sensor::ReceiveEventSensorData::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void Sensor::ReadDataSensorData(ara::com::SamplePtr<sensor::service::proxy::events::SensorData::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();

    if (m_receiverSensorData)
    {
        m_receiverSensorData(data);
    }
}
 
void Sensor::RegistEventHandlerSensorData(std::function<void(const sensor::service::proxy::events::SensorData::SampleType&)> handler)
{
    m_receiverSensorData = handler;
}
 
void Sensor::RequestCalculation(const float& factor, const float& offset)
{
    if (m_found)
    {
        auto request = m_interface->Calculation(factor, offset);
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "Sensor::RequestCalculation::Responded";
            
            auto result = response.Value();
            if (m_responderCalculation)
            {
                m_responderCalculation(result);
            }
        }
        else
        {
            m_logger.LogError() << "Sensor::RequestCalculation::" << response.Error().Message();
        }
    }
}
 
void Sensor::RegistResponseHandlerCalculation(std::function<void(const sensor::service::proxy::methods::Calculation::Output&)> handler)
{
    m_responderCalculation = handler;
}
 
} /// namespace port
} /// namespace aa
} /// namespace actuator
 
/// EOF