# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ruy::ruy_trace ruy::ruy_platform ruy::ruy_check_macros ruy::ruy_opt_set ruy::ruy_time ruy::ruy_wait ruy::ruy_size_util ruy::ruy_tune ruy::ruy_system_aligned_alloc ruy::ruy_prepacked_cache ruy::ruy_allocator ruy::ruy_side_pair ruy::ruy_block_map ruy::ruy_blocking_counter ruy::ruy_thread_pool ruy::ruy_cpu_cache_params ruy::ruy_cpuinfo ruy::ruy_path ruy::ruy_denormal ruy::ruy_performance_advisory ruy::ruy_matrix ruy::ruy_mul_params ruy::ruy_mat ruy::ruy_asm_helpers ruy::ruy_apply_multiplier ruy::ruy_kernel_common ruy::ruy_pack_common ruy::ruy_kernel_arm ruy::ruy_pack_arm ruy::ruy_kernel_avx512 ruy::ruy_pack_avx512 ruy::ruy_have_built_path_for_avx512 ruy::ruy_kernel_avx2_fma ruy::ruy_pack_avx2_fma ruy::ruy_have_built_path_for_avx2_fma ruy::ruy_kernel_avx ruy::ruy_pack_avx ruy::ruy_have_built_path_for_avx ruy::ruy_kernel ruy::ruy_pack ruy::ruy_have_built_path_for ruy::ruy_context ruy::ruy_ctx ruy::ruy_context_get_ctx ruy::ruy_trmul_params ruy::ruy_trmul ruy::ruy_prepare_packed_matrices ruy::ruy_create_trmul_params ruy::ruy_validate ruy::ruy_frontend ruy::ruy ruy::ruy_reference_mul ruy::ruy_profiler_instrumentation ruy::ruy_profiler_profiler)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target ruy::ruy_trace
add_library(ruy::ruy_trace INTERFACE IMPORTED)

set_target_properties(ruy::ruy_trace PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_side_pair"
)

# Create imported target ruy::ruy_platform
add_library(ruy::ruy_platform INTERFACE IMPORTED)

set_target_properties(ruy::ruy_platform PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_check_macros
add_library(ruy::ruy_check_macros INTERFACE IMPORTED)

set_target_properties(ruy::ruy_check_macros PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_opt_set
add_library(ruy::ruy_opt_set INTERFACE IMPORTED)

set_target_properties(ruy::ruy_opt_set PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_time
add_library(ruy::ruy_time INTERFACE IMPORTED)

set_target_properties(ruy::ruy_time PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_wait
add_library(ruy::ruy_wait STATIC IMPORTED)

set_target_properties(ruy::ruy_wait PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_time;\$<LINK_ONLY:-pthread>"
)

# Create imported target ruy::ruy_size_util
add_library(ruy::ruy_size_util INTERFACE IMPORTED)

set_target_properties(ruy::ruy_size_util PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros"
)

# Create imported target ruy::ruy_tune
add_library(ruy::ruy_tune STATIC IMPORTED)

set_target_properties(ruy::ruy_tune PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_cpu_cache_params;ruy::ruy_cpuinfo;ruy::ruy_opt_set;ruy::ruy_platform;ruy::ruy_time"
)

# Create imported target ruy::ruy_system_aligned_alloc
add_library(ruy::ruy_system_aligned_alloc STATIC IMPORTED)

set_target_properties(ruy::ruy_system_aligned_alloc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_prepacked_cache
add_library(ruy::ruy_prepacked_cache STATIC IMPORTED)

set_target_properties(ruy::ruy_prepacked_cache PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_mat;ruy::ruy_system_aligned_alloc;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_allocator
add_library(ruy::ruy_allocator STATIC IMPORTED)

set_target_properties(ruy::ruy_allocator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_opt_set;ruy::ruy_size_util;ruy::ruy_system_aligned_alloc"
)

# Create imported target ruy::ruy_side_pair
add_library(ruy::ruy_side_pair INTERFACE IMPORTED)

set_target_properties(ruy::ruy_side_pair PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros"
)

# Create imported target ruy::ruy_block_map
add_library(ruy::ruy_block_map STATIC IMPORTED)

set_target_properties(ruy::ruy_block_map PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_cpu_cache_params;ruy::ruy_opt_set;ruy::ruy_side_pair;ruy::ruy_size_util;ruy::ruy_trace;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_blocking_counter
add_library(ruy::ruy_blocking_counter STATIC IMPORTED)

set_target_properties(ruy::ruy_blocking_counter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_time;ruy::ruy_wait;\$<LINK_ONLY:-pthread>"
)

# Create imported target ruy::ruy_thread_pool
add_library(ruy::ruy_thread_pool STATIC IMPORTED)

set_target_properties(ruy::ruy_thread_pool PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_blocking_counter;ruy::ruy_check_macros;ruy::ruy_denormal;ruy::ruy_time;ruy::ruy_trace;ruy::ruy_wait;\$<LINK_ONLY:-pthread>"
)

# Create imported target ruy::ruy_cpu_cache_params
add_library(ruy::ruy_cpu_cache_params INTERFACE IMPORTED)

set_target_properties(ruy::ruy_cpu_cache_params PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_cpuinfo
add_library(ruy::ruy_cpuinfo STATIC IMPORTED)

set_target_properties(ruy::ruy_cpuinfo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_platform;ruy::ruy_check_macros;ruy::ruy_cpu_cache_params;cpuinfo::cpuinfo"
)

# Create imported target ruy::ruy_path
add_library(ruy::ruy_path INTERFACE IMPORTED)

set_target_properties(ruy::ruy_path PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_platform;ruy::ruy_size_util"
)

# Create imported target ruy::ruy_denormal
add_library(ruy::ruy_denormal STATIC IMPORTED)

set_target_properties(ruy::ruy_denormal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_performance_advisory
add_library(ruy::ruy_performance_advisory INTERFACE IMPORTED)

set_target_properties(ruy::ruy_performance_advisory PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ruy::ruy_matrix
add_library(ruy::ruy_matrix INTERFACE IMPORTED)

set_target_properties(ruy::ruy_matrix PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros"
)

# Create imported target ruy::ruy_mul_params
add_library(ruy::ruy_mul_params INTERFACE IMPORTED)

set_target_properties(ruy::ruy_mul_params PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_size_util"
)

# Create imported target ruy::ruy_mat
add_library(ruy::ruy_mat INTERFACE IMPORTED)

set_target_properties(ruy::ruy_mat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_matrix;ruy::ruy_size_util"
)

# Create imported target ruy::ruy_asm_helpers
add_library(ruy::ruy_asm_helpers INTERFACE IMPORTED)

set_target_properties(ruy::ruy_asm_helpers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_opt_set"
)

# Create imported target ruy::ruy_apply_multiplier
add_library(ruy::ruy_apply_multiplier STATIC IMPORTED)

set_target_properties(ruy::ruy_apply_multiplier PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mul_params"
)

# Create imported target ruy::ruy_kernel_common
add_library(ruy::ruy_kernel_common INTERFACE IMPORTED)

set_target_properties(ruy::ruy_kernel_common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_apply_multiplier;ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_side_pair;ruy::ruy_size_util;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack_common
add_library(ruy::ruy_pack_common INTERFACE IMPORTED)

set_target_properties(ruy::ruy_pack_common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_kernel_arm
add_library(ruy::ruy_kernel_arm STATIC IMPORTED)

set_target_properties(ruy::ruy_kernel_arm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_asm_helpers;ruy::ruy_check_macros;ruy::ruy_kernel_common;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_side_pair;ruy::ruy_size_util;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack_arm
add_library(ruy::ruy_pack_arm STATIC IMPORTED)

set_target_properties(ruy::ruy_pack_arm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_asm_helpers;ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_opt_set;ruy::ruy_pack_common;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_kernel_avx512
add_library(ruy::ruy_kernel_avx512 STATIC IMPORTED)

set_target_properties(ruy::ruy_kernel_avx512 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_kernel_common;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack_avx512
add_library(ruy::ruy_pack_avx512 STATIC IMPORTED)

set_target_properties(ruy::ruy_pack_avx512 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_opt_set;ruy::ruy_pack_common;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_have_built_path_for_avx512
add_library(ruy::ruy_have_built_path_for_avx512 STATIC IMPORTED)

set_target_properties(ruy::ruy_have_built_path_for_avx512 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_opt_set;ruy::ruy_platform"
)

# Create imported target ruy::ruy_kernel_avx2_fma
add_library(ruy::ruy_kernel_avx2_fma STATIC IMPORTED)

set_target_properties(ruy::ruy_kernel_avx2_fma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_kernel_common;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack_avx2_fma
add_library(ruy::ruy_pack_avx2_fma STATIC IMPORTED)

set_target_properties(ruy::ruy_pack_avx2_fma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_opt_set;ruy::ruy_pack_common;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_have_built_path_for_avx2_fma
add_library(ruy::ruy_have_built_path_for_avx2_fma STATIC IMPORTED)

set_target_properties(ruy::ruy_have_built_path_for_avx2_fma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_opt_set;ruy::ruy_platform"
)

# Create imported target ruy::ruy_kernel_avx
add_library(ruy::ruy_kernel_avx STATIC IMPORTED)

set_target_properties(ruy::ruy_kernel_avx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_kernel_common;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack_avx
add_library(ruy::ruy_pack_avx STATIC IMPORTED)

set_target_properties(ruy::ruy_pack_avx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_opt_set;ruy::ruy_pack_common;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_have_built_path_for_avx
add_library(ruy::ruy_have_built_path_for_avx STATIC IMPORTED)

set_target_properties(ruy::ruy_have_built_path_for_avx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_opt_set;ruy::ruy_platform"
)

# Create imported target ruy::ruy_kernel
add_library(ruy::ruy_kernel INTERFACE IMPORTED)

set_target_properties(ruy::ruy_kernel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_apply_multiplier;ruy::ruy_check_macros;ruy::ruy_kernel_arm;ruy::ruy_kernel_avx;ruy::ruy_kernel_avx2_fma;ruy::ruy_kernel_avx512;ruy::ruy_kernel_common;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_side_pair;ruy::ruy_size_util;ruy::ruy_trace;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_pack
add_library(ruy::ruy_pack INTERFACE IMPORTED)

set_target_properties(ruy::ruy_pack PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_opt_set;ruy::ruy_pack_arm;ruy::ruy_pack_avx;ruy::ruy_pack_avx2_fma;ruy::ruy_pack_avx512;ruy::ruy_pack_common;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_trace;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_have_built_path_for
add_library(ruy::ruy_have_built_path_for INTERFACE IMPORTED)

set_target_properties(ruy::ruy_have_built_path_for PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_have_built_path_for_avx;ruy::ruy_have_built_path_for_avx2_fma;ruy::ruy_have_built_path_for_avx512;ruy::ruy_platform"
)

# Create imported target ruy::ruy_context
add_library(ruy::ruy_context STATIC IMPORTED)

set_target_properties(ruy::ruy_context PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_check_macros;ruy::ruy_ctx;ruy::ruy_path;ruy::ruy_performance_advisory;ruy::ruy_platform;ruy::ruy_prepacked_cache;ruy::ruy_thread_pool;ruy::ruy_tune"
)

# Create imported target ruy::ruy_ctx
add_library(ruy::ruy_ctx STATIC IMPORTED)

set_target_properties(ruy::ruy_ctx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_check_macros;ruy::ruy_cpuinfo;ruy::ruy_have_built_path_for;ruy::ruy_path;ruy::ruy_performance_advisory;ruy::ruy_platform;ruy::ruy_prepacked_cache;ruy::ruy_thread_pool;ruy::ruy_trace;ruy::ruy_tune"
)

# Create imported target ruy::ruy_context_get_ctx
add_library(ruy::ruy_context_get_ctx STATIC IMPORTED)

set_target_properties(ruy::ruy_context_get_ctx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_context;ruy::ruy_ctx"
)

# Create imported target ruy::ruy_trmul_params
add_library(ruy::ruy_trmul_params INTERFACE IMPORTED)

set_target_properties(ruy::ruy_trmul_params PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_path;ruy::ruy_side_pair;ruy::ruy_tune"
)

# Create imported target ruy::ruy_trmul
add_library(ruy::ruy_trmul STATIC IMPORTED)

set_target_properties(ruy::ruy_trmul PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_block_map;ruy::ruy_check_macros;ruy::ruy_cpu_cache_params;ruy::ruy_cpuinfo;ruy::ruy_ctx;ruy::ruy_denormal;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_mul_params;ruy::ruy_opt_set;ruy::ruy_side_pair;ruy::ruy_size_util;ruy::ruy_thread_pool;ruy::ruy_trace;ruy::ruy_trmul_params;ruy::ruy_tune;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy_prepare_packed_matrices
add_library(ruy::ruy_prepare_packed_matrices STATIC IMPORTED)

set_target_properties(ruy::ruy_prepare_packed_matrices PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_ctx;ruy::ruy_matrix;ruy::ruy_prepacked_cache;ruy::ruy_side_pair;ruy::ruy_trace;ruy::ruy_trmul_params"
)

# Create imported target ruy::ruy_create_trmul_params
add_library(ruy::ruy_create_trmul_params INTERFACE IMPORTED)

set_target_properties(ruy::ruy_create_trmul_params PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_check_macros;ruy::ruy_ctx;ruy::ruy_kernel;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_pack;ruy::ruy_path;ruy::ruy_performance_advisory;ruy::ruy_platform;ruy::ruy_side_pair;ruy::ruy_trace;ruy::ruy_trmul_params"
)

# Create imported target ruy::ruy_validate
add_library(ruy::ruy_validate INTERFACE IMPORTED)

set_target_properties(ruy::ruy_validate PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_side_pair"
)

# Create imported target ruy::ruy_frontend
add_library(ruy::ruy_frontend STATIC IMPORTED)

set_target_properties(ruy::ruy_frontend PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_allocator;ruy::ruy_create_trmul_params;ruy::ruy_ctx;ruy::ruy_mat;ruy::ruy_mul_params;ruy::ruy_prepare_packed_matrices;ruy::ruy_trace;ruy::ruy_trmul;ruy::ruy_trmul_params;ruy::ruy_validate;ruy::ruy_profiler_instrumentation"
)

# Create imported target ruy::ruy
add_library(ruy::ruy INTERFACE IMPORTED)

set_target_properties(ruy::ruy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_check_macros;ruy::ruy_context;ruy::ruy_context_get_ctx;ruy::ruy_frontend;ruy::ruy_mat;ruy::ruy_matrix;ruy::ruy_mul_params;ruy::ruy_path;ruy::ruy_platform;ruy::ruy_size_util;ruy::ruy_trace"
)

# Create imported target ruy::ruy_reference_mul
add_library(ruy::ruy_reference_mul INTERFACE IMPORTED)

set_target_properties(ruy::ruy_reference_mul PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_apply_multiplier;ruy::ruy_matrix;ruy::ruy_mul_params"
)

# Create imported target ruy::ruy_profiler_instrumentation
add_library(ruy::ruy_profiler_instrumentation STATIC IMPORTED)

set_target_properties(ruy::ruy_profiler_instrumentation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-pthread>"
)

# Create imported target ruy::ruy_profiler_profiler
add_library(ruy::ruy_profiler_profiler STATIC IMPORTED)

set_target_properties(ruy::ruy_profiler_profiler PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ruy::ruy_profiler_instrumentation;\$<LINK_ONLY:-pthread>"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/ruyTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "cpuinfo::cpuinfo" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
