/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: dds_service_announcement_message.idl
  Source: dds_service_announcement_message.cpp
  Cyclone DDS: v0.10.4

*****************************************************************/
#include "dds_service_announcement_message.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
::dds::ara::com::ServiceInstanceResourceIdentifierType enum_conversion<::dds::ara::com::ServiceInstanceResourceIdentifierType>(uint32_t in) {
  switch (in) {
    default:
    case 0:
    return ::dds::ara::com::ServiceInstanceResourceIdentifierType::SERVICE_INSTANCE_RESOURCE_PARTITION;
    break;
    case 1:
    return ::dds::ara::com::ServiceInstanceResourceIdentifierType::SERVICE_INSTANCE_RESOURCE_TOPIC_PREFIX;
    break;
    case 2:
    return ::dds::ara::com::ServiceInstanceResourceIdentifierType::SERVICE_INSTANCE_RESOURCE_INSTANCE_ID;
    break;
  }
}

template<>
propvec &get_type_props<::dds::ara::com::ServiceVersion>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::major_version
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::minor_version

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

template<>
propvec &get_type_props<::dds::ara::com::ServiceAnnouncementMessage>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bb_unset, extensibility::ext_final, false));  //::interface_id
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint16_t>(), extensibility::ext_final, false));  //::instance_id
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<::dds::ara::com::ServiceVersion>(), extensibility::ext_final, false));  //::version
  entity_properties_t::append_struct_contents(props, get_type_props<::dds::ara::com::ServiceVersion>());  //internal contents of ::version
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<::dds::ara::com::ServiceInstanceResourceIdentifierType>(), extensibility::ext_final, false));  //::identifier_type
  keylist.add_key_endpoint(std::list<uint32_t>{0});
  keylist.add_key_endpoint(std::list<uint32_t>{1});

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

