/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: impl_type_imagedata.idl
  Source: impl_type_imagedata.cpp
  Cyclone DDS: v0.10.4

*****************************************************************/
#include "impl_type_imagedata.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

