///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor_proxy.h
/// SERVICE INTERFACE NAME            : Sensor
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_SENSOR_SERVICE_SERVICE_INTERFACE_SENSOR_PROXY_H
#define PARA_COM_GEN_SENSOR_SERVICE_SERVICE_INTERFACE_SENSOR_PROXY_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_01004}
#include "sensor_common.h"
#include "para/com/proxy/proxy_interface.h"
/// @uptrace{SWS_CM_01005}
namespace sensor
{
namespace service
{
/// @uptrace{SWS_CM_01007}
namespace proxy
{
/// @uptrace{SWS_CM_01009}
namespace events
{
/// @uptrace{SWS_CM_00003}
class SensorData
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = float;
    /// @brief Constructor
    explicit SensorData(para::com::ProxyInterface* interface, para::com::ProxyDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
    }
    /// @brief Destructor
    virtual ~SensorData() = default;
    /// @brief Delete copy constructor
    SensorData(const SensorData& other) = delete;
    /// @brief Delete copy assignment
    SensorData& operator=(const SensorData& other) = delete;
    /// @brief Move constructor
    SensorData(SensorData&& other) noexcept 
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
        mMaxSampleCount = other.mMaxSampleCount;
        mEventReceiveHandler = other.mEventReceiveHandler;
        mSubscriptionStateChangeHandler = other.mSubscriptionStateChangeHandler;
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mDdsInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Move assignment
    SensorData& operator=(SensorData&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        mMaxSampleCount = other.mMaxSampleCount;
        mEventReceiveHandler = other.mEventReceiveHandler;
        mSubscriptionStateChangeHandler = other.mSubscriptionStateChangeHandler;
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
                mDdsInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        return *this;
    }
    /// @brief Requests "Subscribe" message to Communication Management
    /// @uptrace{SWS_CM_00141}
    ara::core::Result<void> Subscribe(size_t maxSampleCount)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                if (mInterface->GetSubscriptionState(kCallSign) == ara::com::SubscriptionState::kSubscribed)
                {
                    if ((maxSampleCount != 0) && (maxSampleCount != mMaxSampleCount))
                    {
                        return ara::core::Result<void>(ara::com::ComErrc::kMaxSampleCountNotRealizable);
                    }
                }
                mMaxSampleCount = maxSampleCount;
                return mInterface->SubscribeEvent(kCallSign, mMaxSampleCount);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                if (mInterface->GetSubscriptionState(kCallSign) == ara::com::SubscriptionState::kSubscribed)
                {
                    if ((maxSampleCount != 0) && (maxSampleCount != mMaxSampleCount))
                    {
                        return ara::core::Result<void>(ara::com::ComErrc::kMaxSampleCountNotRealizable);
                    }
                }
                mMaxSampleCount = maxSampleCount;
                return mInterface->SubscribeEvent(kCallSign, mMaxSampleCount);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                if (mDdsInterface->GetSubscriptionState(kCallSign) == ara::com::SubscriptionState::kSubscribed)
                {
                    if ((maxSampleCount != 0) && (maxSampleCount != mMaxSampleCount))
                    {
                        return ara::core::Result<void>(ara::com::ComErrc::kMaxSampleCountNotRealizable);
                    }
                }
                mMaxSampleCount = maxSampleCount;
                return mDdsInterface->SubscribeEvent<dds::ara::com::Float32EventType>(kCallSign, mMaxSampleCount);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief Requests "StopSubscribe" message to Communication Management
    /// @uptrace{SWS_CM_00151}
    void Unsubscribe()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->UnsubscribeEvent(kCallSign);
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->UnsubscribeEvent(kCallSign);
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->UnsubscribeEvent(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Return state for current subscription
    /// @uptrace{SWS_CM_00316}
    ara::com::SubscriptionState GetSubscriptionState() const
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->GetSubscriptionState(kCallSign);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->GetSubscriptionState(kCallSign);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return mDdsInterface->GetSubscriptionState(kCallSign);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::com::SubscriptionState::kNotSubscribed;
        }
    }
    /// @brief Register callback to catch changes of subscription state
    /// @uptrace{SWS_CM_00333}
    ara::core::Result<void> SetSubscriptionStateChangeHandler(ara::com::SubscriptionStateChangeHandler handler)
    {
        mSubscriptionStateChangeHandler = std::move(handler);
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return mDdsInterface->SetSubscriptionStateChangeHandler(kCallSign, mSubscriptionStateChangeHandler);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief Unset bound callback by SetSubscriptionStateChangeHandler
    /// @uptrace{SWS_CM_00334}
    void UnsetSubscriptionStateChangeHandler()
    {
        mSubscriptionStateChangeHandler = nullptr;
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->UnsetSubscriptionStateChangeHandler(kCallSign);
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->UnsetSubscriptionStateChangeHandler(kCallSign);
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->UnsetSubscriptionStateChangeHandler(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Get received event data from cache
    /// @uptrace{SWS_CM_00701}
    template<typename F>
    ara::core::Result<size_t> GetNewSamples(F&& f, size_t maxNumberOfSamples = std::numeric_limits<size_t>::max())
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                auto samples = mInterface->GetNewSamples(kCallSign, maxNumberOfSamples);
                for (const auto& sample : samples)
                {
                    para::serializer::Deserializer deserializer{sample};
                    SampleType data;
                    deserializer.read(props, data);
                    f(ara::com::make_sample_ptr<const SampleType>(data));
                }
                return samples.size();
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                auto samples = mInterface->GetNewSamples(kCallSign, maxNumberOfSamples);
                for (const auto& sample : samples)
                {
                    para::serializer::Deserializer deserializer{sample};
                    SampleType data;
                    deserializer.read(props, data);
                    f(ara::com::make_sample_ptr<const SampleType>(data));
                }
                return samples.size();
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                auto samples = mDdsInterface->GetNewSamples<dds::ara::com::Float32EventType>(kCallSign, maxNumberOfSamples);
                for (const auto& sample : samples)
                {
                    SampleType data = sample.data();
                    f(ara::com::make_sample_ptr<const SampleType>(data));
                }
                return samples.size();
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<size_t>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief Register callback to catch that event data is received
    /// @uptrace{SWS_CM_00181}
    ara::core::Result<void> SetReceiveHandler(ara::com::EventReceiveHandler handler)
    {
        mEventReceiveHandler = std::move(handler);
        switch(mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return mDdsInterface->SetEventReceiveHandler(kCallSign, mEventReceiveHandler);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief Unset bound callback by SetReceiveHandler
    /// @uptrace{SWS_CM_00183}
    ara::core::Result<void> UnsetReceiveHandler()
    {
        mEventReceiveHandler = nullptr;
        switch(mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->UnsetEventReceiveHandler(kCallSign);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->UnsetEventReceiveHandler(kCallSign);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return mDdsInterface->UnsetEventReceiveHandler(kCallSign);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief Returns the count of free event cache
    /// @uptrace{SWS_CM_00705}
    ara::core::Result<size_t> GetFreeSampleCount() const noexcept
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                auto ret = mInterface->GetFreeSampleCount(kCallSign);
                if (ret < 0)
                {
                    return ara::core::Result<size_t>(ara::core::CoreErrc::kInvalidArgument);
                }
                return ret;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                auto ret = mInterface->GetFreeSampleCount(kCallSign);
                if (ret < 0)
                {
                    return ara::core::Result<size_t>(ara::core::CoreErrc::kInvalidArgument);
                }
                return ret;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                auto ret = mDdsInterface->GetFreeSampleCount(kCallSign);
                if (ret < 0)
                {
                    return ara::core::Result<size_t>(ara::core::CoreErrc::kInvalidArgument);
                }
                return ret;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<size_t>(ara::core::CoreErrc::kInvalidArgument);
        }
    }
    /// @brief This method provides access to the global SMState of the this Method class,
    ///        which was determined by the last run of E2E_check function invoked during the last reception of the method response.
    /// @uptrace{SWS_CM_10475}
    /// @uptrace{SWS_CM_90431}
    ara::com::e2e::SMState GetSMState() const noexcept
    {
        switch(mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->GetE2EStateMachineState(kCallSign);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->GetE2EStateMachineState(kCallSign);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return ara::com::e2e::SMState::kStateMDisabled;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::com::e2e::SMState::kStateMDisabled;
        }
    }
    
private:
    para::com::ProxyInterface* mInterface;
    para::com::ProxyDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    size_t mMaxSampleCount{0};
    ara::com::EventReceiveHandler mEventReceiveHandler{nullptr};
    ara::com::SubscriptionStateChangeHandler mSubscriptionStateChangeHandler{nullptr};
    const std::string kCallSign = {"SensorData"};
};
} /// namespace events
/// @uptrace{SWS_CM_01031}
namespace fields
{
} /// namespace fields
/// @uptrace{SWS_CM_01015}
namespace methods
{
/// @uptrace{SWS_CM_00006}
class Calculation
{
public:
    /// @brief Container for OUT arguments
    /// @uptrace{SWS_CM_00196}
    struct Output
    {
        float result;
    };
    /// @brief Constructor
    explicit Calculation(para::com::ProxyInterface* interface, para::com::ProxyDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~Calculation() = default;
    /// @brief
    Calculation(const Calculation& other) = delete;
    Calculation& operator=(const Calculation& other) = delete;
    /// @brief Move constructor
    Calculation(Calculation&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Move assignment
    Calculation& operator=(Calculation&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodReturnHandler(kCallSign, [](std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData) {
                    HandleMethodReturn(result, data, userData);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        return *this;
    }
    /// @brief Function call operator
    /// @uptrace{SWS_CM_00196}
    ara::core::Future<Output> operator()(const float& factor, const float& offset)
    {
        auto* __promise__ = new ara::core::Promise<Output>();
        auto __future__ = __promise__->get_future();
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer __serializer__{};
                __serializer__.write(props, factor);
                __serializer__.write(props, offset);
                auto __data__ = __serializer__.ensure();
                mInterface->CallMethod(kCallSign, __data__, __promise__);
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer __serializer__{};
                __serializer__.write(props, factor);
                __serializer__.write(props, offset);
                auto __data__ = __serializer__.ensure();
                mInterface->CallMethod(kCallSign, __data__, __promise__);
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::sensor::service::SensorMethod_Calculation_In _in_args_;
                _in_args_.factor() = factor;
                _in_args_.offset() = offset;
                dds::sensor::service::SensorMethod_Call _call_{};
                _call_.Calculation(_in_args_, dds::sensor::service::SensorMethod_Calculation_Hash);
                dds::sensor::service::SensorMethod_Request _request_{};
                _request_.header() = mDdsInterface->GetMethodRequestHeader();
                _request_.data() = _call_;
                mDdsInterface->CallMethod<dds::sensor::service::SensorMethod_Request>(_request_.header(), _request_, __promise__);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default :
                __promise__->SetError(ara::com::ComErrc::kNetworkBindingFailure);
                break;
        }
        return __future__;
    }
    /// @brief This method provides access to the global SMState of the this Method class,
    ///        which was determined by the last run of E2E_check function invoked during the last reception of the method response.
    /// @uptrace{SWS_CM_90483}
    /// @uptrace{SWS_CM_90484}
    ara::com::e2e::SMState GetSMState() const noexcept
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->GetE2EStateMachineState(kCallSign);;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                return mInterface->GetE2EStateMachineState(kCallSign);;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                return ara::com::e2e::SMState::kStateMDisabled;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::com::e2e::SMState::kStateMDisabled;
        }
    }
    #ifdef PARA_DDS_IMPLEMENTATION
    /// @brief Function call operator for DDS
    void HandleMethodReturn(dds::ReturnCode_t result, const dds::sensor::service::SensorMethod_Calculation_Result& data, void* userData)
    {
        auto* promise = static_cast<ara::core::Promise<Calculation::Output>*>(userData);
        if (result == dds::RETCODE_OK)
        {
            dds::sensor::service::SensorMethod_Calculation_Out _response_ = data.result();
            methods::Calculation::Output _out_args_;
            _out_args_.result = _response_.result();
            
            promise->set_value(_out_args_);
        }
        else
        {
            dds::ara::core::ErrorCode errorData = data.error();
            ara::core::ErrorDomain::IdType domainId = errorData.error_domain_value();
            ara::core::ErrorDomain::CodeType errorCode = errorData.error_code();
            switch (domainId)
            {
                default:
                {
                    promise->SetError(ara::com::ComErrc::kUnsetFailure);
                    break;
                }
            }
        }
        delete static_cast<ara::core::Promise<Calculation::Output>*>(userData);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    
private:
    static void HandleMethodReturn(std::uint8_t result, const std::vector<std::uint8_t>& data, void* userData)
    {
        const para::serializer::TransformationProps props{};
        auto* promise = static_cast<ara::core::Promise<Calculation::Output>*>(userData);
        if (result == 0)
        {
            para::serializer::Deserializer deserializer{data};
            Calculation::Output output;
            deserializer.read(props, output.result);
            promise->set_value(output);
        }
        else
        {
            para::serializer::Deserializer deserializer{data};
            para::serializer::ApplicationMethodError applicationMethodError;
            deserializer.read(para::serializer::Serializer::getApplicationMethodErrorProps(), applicationMethodError);
            para::serializer::ApplicationMethodErrorData errorData = std::get<para::serializer::ApplicationMethodErrorData>(applicationMethodError);
            ara::core::ErrorDomain::IdType domainId = errorData.domainId;
            ara::core::ErrorDomain::CodeType errorCode = errorData.errorCode;
            switch (domainId)
            {
                default:
                {
                    promise->SetError(ara::com::ComErrc::kUnsetFailure);
                    break;
                }
            }
        }
        delete static_cast<ara::core::Promise<Calculation::Output>*>(userData);
    }
    para::com::ProxyInterface* mInterface;
    para::com::ProxyDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign{"Calculation"};
};
} /// namespace methods
/// @uptrace{SWS_CM_00004}
class SensorProxy
{
public: 
    /// @uptrace{SWS_CM_00312}
    class HandleType
    {
    public:
        HandleType() = default;
        HandleType(ara::core::InstanceSpecifier instanceSpecifier, para::com::ServiceHandle service)
            : mInstanceSpecifier(std::move(instanceSpecifier))
            , mServiceHandle(service)
        {
        }
        ~HandleType() = default;
        /// @uptrace{SWS_CM_00317}
        HandleType(const HandleType& other) = default;
        HandleType& operator=(const HandleType& other) = default;
        /// @uptrace{SWS_CM_00318}
        HandleType(HandleType&& other) = default;
        HandleType& operator=(HandleType&& other) = default;
        /// @brief Return instance specifier
        ara::core::InstanceSpecifier GetInstanceSpecifier()
        {
            return mInstanceSpecifier;
        }
        /// @brief Return handle for bound service
        para::com::ServiceHandle GetServiceHandle()
        {
            return mServiceHandle;
        }
        /// @brief Is equal to operator
        inline bool operator==(const HandleType& other) const
        {
            return mInstanceSpecifier == other.mInstanceSpecifier && mServiceHandle == other.mServiceHandle;
        }
        /// @brief Less than operator
        inline bool operator<(const HandleType& other) const
        {
            return mServiceHandle.version < other.mServiceHandle.version;
        }
        
    private:
        ara::core::InstanceSpecifier mInstanceSpecifier{"undefined"};
        para::com::ServiceHandle mServiceHandle;
    };
    /// @brief Requests "FindService" message to Communication Management with callback
    /// @uptrace{SWS_CM_00623}
    static ara::core::Result<ara::com::FindServiceHandle> StartFindService(ara::com::FindServiceHandler<SensorProxy::HandleType> handler, ara::core::InstanceSpecifier instanceSpec)
    {
        switch (para::com::GetServiceProtocol(instanceSpec))
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                ara::com::FindServiceHandle findHandle = para::com::ProxyInterface::GetFindServiceHandle(instanceSpec);
                auto findCallback = [&, handler, findHandle, instanceSpec](std::vector<para::com::ServiceHandle> services) {
                    ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                    for (auto& service : services)
                    {
                        handleContainer.emplace_back(instanceSpec, service);
                    }
                    handler(handleContainer, findHandle);
                };
                return para::com::ProxyInterface::StartFindService(instanceSpec, findCallback);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                ara::com::FindServiceHandle findHandle = para::com::ProxyInterface::GetFindServiceHandle(instanceSpec);
                auto findCallback = [&, handler, findHandle, instanceSpec](std::vector<para::com::ServiceHandle> services) {
                    ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                    for (auto& service : services)
                    {
                        handleContainer.emplace_back(instanceSpec, service);
                    }
                    handler(handleContainer, findHandle);
                };
                return para::com::ProxyInterface::StartFindService(instanceSpec, findCallback);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                ara::com::FindServiceHandle findHandle = para::com::ProxyDdsInterface::GetFindServiceHandle(instanceSpec);
                auto findCallback = [&, handler, findHandle, instanceSpec](std::vector<para::com::ServiceHandle> services) {
                    ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                    for (auto& service : services)
                    {
                        handleContainer.emplace_back(instanceSpec, service);
                    }
                    handler(handleContainer, findHandle);
                };
                return para::com::ProxyDdsInterface::StartFindService(instanceSpec, findCallback);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<ara::com::FindServiceHandle>::FromError(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Send "FindService" message to Communication Management at once
    /// @uptrace{SWS_CM_00622}
    static ara::core::Result<ara::com::ServiceHandleContainer<SensorProxy::HandleType>> FindService(ara::core::InstanceSpecifier instanceSpec)
    {
        switch(para::com::GetServiceProtocol(instanceSpec))
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                auto result = para::com::ProxyInterface::FindService(instanceSpec);
                if (!result.HasValue())
                {
                    return ara::core::Result<ara::com::ServiceHandleContainer<SensorProxy::HandleType>>::FromError(result.Error());
                }
                ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                const auto& services = result.Value();
                for (auto& service : services)
                {
                    handleContainer.emplace_back(instanceSpec, service);
                }
                return handleContainer;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                auto result = para::com::ProxyInterface::FindService(instanceSpec);
                if (!result.HasValue())
                {
                    return ara::core::Result<ara::com::ServiceHandleContainer<SensorProxy::HandleType>>::FromError(result.Error());
                }
                ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                const auto& services = result.Value();
                for (auto& service : services)
                {
                    handleContainer.emplace_back(instanceSpec, service);
                }
                return handleContainer;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                auto result = para::com::ProxyDdsInterface::FindService(instanceSpec);
                if (!result.HasValue())
                {
                    return ara::core::Result<ara::com::ServiceHandleContainer<SensorProxy::HandleType>>::FromError(result.Error());
                }
                ara::com::ServiceHandleContainer<SensorProxy::HandleType> handleContainer;
                const auto& services = result.Value();
                for (auto& service : services)
                {
                    handleContainer.emplace_back(instanceSpec, service);
                }
                return handleContainer;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<ara::com::ServiceHandleContainer<SensorProxy::HandleType>>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Constructor
    /// @note This function shall be called after processing of FindService/StartFindService was completed
    /// @uptrace{SWS_CM_00004, SWS_CM_00131}
    explicit SensorProxy(HandleType& handle)
        : mHandle(handle)
        , mInterface(std::make_unique<para::com::ProxyInterface>(handle.GetInstanceSpecifier(), handle.GetServiceHandle()))
        , mDdsInterface(std::make_unique<para::com::ProxyDdsInterface>(handle.GetInstanceSpecifier(), handle.GetServiceHandle()))
        , SensorData(mInterface.get(), mDdsInterface.get(), mHandle.GetServiceHandle().protocol)
        , Calculation(mInterface.get(), mDdsInterface.get(), mHandle.GetServiceHandle().protocol)
    {
        #ifdef PARA_DDS_IMPLEMENTATION
        if (mHandle.GetServiceHandle().protocol == para::com::ServiceProtocol::kDds)
        {
            mDdsInterface->CreateMethods<dds::sensor::service::SensorMethod_Request, dds::sensor::service::SensorMethod_Reply>();
            auto methodReplyHandler = [this] (dds::sub::AnyDataReader& dataReader) {
                dds::sub::DataReader<dds::sensor::service::SensorMethod_Reply> _reader_ = dataReader;
                dds::sub::LoanedSamples<dds::sensor::service::SensorMethod_Reply> _samples_;
                _samples_ = _reader_.take();
                for (auto& _sample_ : _samples_)
                {
                    if (_sample_.info().valid())
                    {
                        auto _reply_ = _sample_.data();
                        auto _userData_ = mDdsInterface->GetMethodPromise(_reply_.header());
                        if (!_userData_.HasValue())
                        {
                            return;
                        }
                        auto _return_ = _reply_.data();
                        switch (_return_._d())
                        {
                            case dds::sensor::service::SensorMethod_Calculation_Hash :
                            {
                                auto _result_ = _return_.Calculation();
                                Calculation.HandleMethodReturn(_result_._d(), _result_, _userData_.Value());
                                break;
                            }
                            default : break;
                        }
                    }
                }
            };
            mDdsInterface->SetMethodReturnHandler(methodReplyHandler);
            mDdsInterface->CreateFields<dds::sensor::service::SensorField_Request, dds::sensor::service::SensorField_Reply>();
            auto fieldReplyHandler = [this] (dds::sub::AnyDataReader& dataReader) {
                dds::sub::DataReader<dds::sensor::service::SensorField_Reply> _reader_ = dataReader;
                dds::sub::LoanedSamples<dds::sensor::service::SensorField_Reply> _samples_;
                _samples_ = _reader_.take();
                for (auto& _sample_ : _samples_)
                {
                    if (_sample_.info().valid())
                    {
                        auto _reply_ = _sample_.data();
                        auto _userData_ = mDdsInterface->GetFieldPromise(_reply_.header());
                        if (!_userData_.HasValue())
                        {
                            return;
                        }
                        auto _return_ = _reply_.data();
                        switch (_return_._d())
                        {
                            default : break;
                        }
                    }
                }
            };
            mDdsInterface->SetFieldReturnHandler(fieldReplyHandler);
        }
        #endif /// PARA_DDS_IMPLEMENTATION
    }
    /// @brief Destructor
    /// @uptrace{SWS_CM_10446}
    ~SensorProxy() = default;
    /// @brief Delete copy constructor
    /// @uptrace{SWS_CM_00136}
    SensorProxy(SensorProxy& other) = delete;
    /// @brief Delete copy assignment
    /// @uptrace{SWS_CM_00136}
    SensorProxy& operator=(const SensorProxy& other) = delete;
    /// @brief Move constructor
    /// @uptrace{SWS_CM_00137}
    SensorProxy(SensorProxy&& other) noexcept
        : mHandle(std::move(other.mHandle))
        , mInterface(std::move(other.mInterface))
        , mDdsInterface(std::move(other.mDdsInterface))
        , SensorData(std::move(other.SensorData))
        , Calculation(std::move(other.Calculation))
    {
        switch (mHandle.GetServiceHandle().protocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopFindService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopFindService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopFindService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
    }
    /// @brief Move assignment
    /// @uptrace{SWS_CM_00137}
    SensorProxy& operator=(SensorProxy&& other) noexcept
    {
        mHandle = std::move(other.mHandle);
        mInterface = std::move(other.mInterface);
        mDdsInterface = std::move(other.mDdsInterface);
        switch (mHandle.GetServiceHandle().protocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopFindService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopFindService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopFindService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        SensorData = std::move(other.SensorData);
        Calculation = std::move(other.Calculation);
        other.mInterface.reset();
        other.mDdsInterface.reset();
        return *this;
    }
    /// @brief Stop the running StartFindService
    /// @uptrace{SWS_CM_00125}
    void StopFindService(ara::com::FindServiceHandle /*handle*/)
    {
        switch (mHandle.GetServiceHandle().protocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopFindService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopFindService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopFindService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Return handle that is connected with service provider currently
    /// @uptrace{SWS_CM_10383}
    HandleType GetHandle() const
    {
        return mHandle;
    }
    
private:
    HandleType mHandle;
    std::unique_ptr<para::com::ProxyInterface> mInterface;
    std::unique_ptr<para::com::ProxyDdsInterface> mDdsInterface;
    
public:
    /// @brief - event, SensorData
    events::SensorData SensorData;
    /// @brief - method, Calculation
    methods::Calculation Calculation;
};
} /// namespace proxy
} /// namespace service
} /// namespace sensor
#endif /// PARA_COM_GEN_sensor_service_SERVICE_INTERFACE_SENSOR_PROXY_H