///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.cpp
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/rootswcomponent/providersensor.h"
#include <opencv2/opencv.hpp>
#include <chrono>
#include <numeric>
#include <algorithm>
#include <cstring>
 
namespace providersensor
{
namespace rootswcomponent
{

// Class names for traffic light detection
const char* ProviderSensor::CLASS_NAMES[6] = {
    "green-lights", "red-lights", "traffic-lights",
    "turn-left", "turn-right", "yellow-lights"
};

// IoU calculation
float ProviderSensor::IoU(const cv::Rect& a, const cv::Rect& b) {
    int x1 = std::max(a.x, b.x);
    int y1 = std::max(a.y, b.y);
    int x2 = std::min(a.x + a.width, b.x + b.width);
    int y2 = std::min(a.y + a.height, b.y + b.height);
    int w = std::max(0, x2 - x1);
    int h = std::max(0, y2 - y1);
    float inter = float(w) * float(h);
    float uni = float(a.area() + b.area()) - inter;
    return uni > 0 ? inter / uni : 0.0f;
}

// Non-Maximum Suppression
std::vector<Det> ProviderSensor::nms(const std::vector<Det>& dets, float iou_thr) {
    if (dets.empty()) return {};
    std::vector<int> idx(dets.size());
    std::iota(idx.begin(), idx.end(), 0);
    std::sort(idx.begin(), idx.end(),
              [&](int a, int b) { return dets[a].score > dets[b].score; });

    std::vector<Det> keep;
    std::vector<char> suppressed(dets.size(), 0);
    for (size_t _i = 0; _i < idx.size(); ++_i) {
        int i = idx[_i];
        if (suppressed[i]) continue;
        keep.push_back(dets[i]);
        for (size_t _j = _i + 1; _j < idx.size(); ++_j) {
            int j = idx[_j];
            if (suppressed[j]) continue;
            if (dets[i].cls == dets[j].cls &&
                IoU(dets[i].rect, dets[j].rect) > iou_thr) {
                suppressed[j] = 1;
            }
        }
    }
    return keep;
}
 
ProviderSensor::ProviderSensor()
    : m_logger(ara::log::CreateLogger("PVSENSR", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
    , m_inputHeight(0)
    , m_inputWidth(0)
    , m_inputChannels(0)
    , m_numClasses(0)
    , m_numDetections(0)
{
}
 
ProviderSensor::~ProviderSensor()
{
}

bool ProviderSensor::InitializeTFLite()
{
    m_logger.LogInfo() << "Initializing TFLite model...";
    
    // Load model from file
    m_model = tflite::FlatBufferModel::BuildFromFile(
        "bestYoloMobilenet_saved_model/bestYoloMobilenet_float16.tflite");
    
    if (!m_model) {
        m_logger.LogError() << "Failed to load TFLite model!";
        return false;
    }
    
    // Build interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    if (tflite::InterpreterBuilder(*m_model, resolver)(&m_interpreter) != kTfLiteOk ||
        !m_interpreter) {
        m_logger.LogError() << "Failed to build TFLite interpreter!";
        return false;
    }
    
    // Set number of threads for inference
    m_interpreter->SetNumThreads(4);
    
    // Allocate tensors
    if (m_interpreter->AllocateTensors() != kTfLiteOk) {
        m_logger.LogError() << "Failed to allocate tensors!";
        return false;
    }
    
    // Get input tensor info
    int in_idx = m_interpreter->inputs()[0];
    TfLiteTensor* in_t = m_interpreter->tensor(in_idx);
    
    if (in_t->type != kTfLiteFloat32 || in_t->dims->size != 4) {
        m_logger.LogError() << "Expected NHWC float32 input tensor!";
        return false;
    }
    
    m_inputHeight = in_t->dims->data[1];
    m_inputWidth = in_t->dims->data[2];
    m_inputChannels = in_t->dims->data[3];
    
    m_logger.LogInfo() << "Input tensor shape: [1, " << m_inputHeight << ", " 
                       << m_inputWidth << ", " << m_inputChannels << "]";
    
    // Get output tensor info
    const auto& outs = m_interpreter->outputs();
    if (outs.size() != 1) {
        m_logger.LogError() << "Expected 1 output tensor, got " << outs.size();
        return false;
    }
    
    int out_idx = outs[0];
    const TfLiteTensor* ot = m_interpreter->tensor(out_idx);
    
    if (ot->type != kTfLiteFloat32 || ot->dims->size != 3 ||
        ot->dims->data[0] != 1 || ot->dims->data[1] != 10) {
        m_logger.LogError() << "Unexpected output shape; need [1, 10, N]";
        return false;
    }
    
    m_numClasses = ot->dims->data[1] - 4;  // 10 - 4 = 6 classes
    m_numDetections = ot->dims->data[2];
    
    m_logger.LogInfo() << "Output tensor shape: [1, " << ot->dims->data[1] 
                       << ", " << m_numDetections << "]";
    m_logger.LogInfo() << "TFLite model initialized successfully!";
    
    return true;
}

std::vector<Det> ProviderSensor::ProcessFrame(const cv::Mat& frame)
{
    std::vector<Det> final_dets;
    
    if (frame.empty() || !m_interpreter) {
        return final_dets;
    }
    
    int H = frame.rows;
    int W = frame.cols;
    
    // Preprocess: resize and convert to float32
    cv::Mat resized;
    cv::resize(frame, resized, cv::Size(m_inputWidth, m_inputHeight));
    
    // BGR -> RGB
    cv::cvtColor(resized, resized, cv::COLOR_BGR2RGB);
    
    // Convert to float32 and normalize to [0, 1]
    cv::Mat f32;
    resized.convertTo(f32, CV_32FC3, 1.0f / 255.0f);
    
    // Copy to input tensor
    std::memcpy(m_interpreter->typed_input_tensor<float>(0),
                f32.data, f32.total() * f32.elemSize());
    
    // Run inference
    if (m_interpreter->Invoke() != kTfLiteOk) {
        m_logger.LogError() << "TFLite inference failed!";
        return final_dets;
    }
    
    // Get output tensor
    int out_idx = m_interpreter->outputs()[0];
    const float* out = m_interpreter->typed_tensor<float>(out_idx);
    
    const int C = 10;  // 4 box coords + 6 classes
    const int N = m_numDetections;
    const int nc = m_numClasses;
    
    // Parse predictions: output is [1, C, N] format
    std::vector<std::array<float, 10>> pred(N);
    for (int c = 0; c < C; ++c) {
        const float* src = out + c * N;
        for (int i = 0; i < N; ++i) {
            float v = src[i];
            // Scale box coordinates to input dimensions
            if (c == 0 || c == 2) v *= (float)m_inputWidth;   // x, w
            if (c == 1 || c == 3) v *= (float)m_inputHeight;  // y, h
            pred[i][c] = v;
        }
    }
    
    // Filter by confidence and create proposals
    std::vector<Det> proposals;
    proposals.reserve(N);
    
    for (int i = 0; i < N; ++i) {
        const auto& p = pred[i];
        
        // Find best class
        int best_cls = -1;
        float best_p = 0.0f;
        for (int c = 0; c < nc; ++c) {
            float pc = p[4 + c];  // Class probabilities at indices 4-9
            if (pc > best_p) {
                best_p = pc;
                best_cls = c;
            }
        }
        
        if (best_p < CONF_THRESHOLD) continue;
        
        // Convert cx, cy, w, h to x1, y1, x2, y2
        float cx = p[0];
        float cy = p[1];
        float bw = p[2];
        float bh = p[3];
        
        float x1 = cx - bw * 0.5f;
        float y1 = cy - bh * 0.5f;
        float x2 = cx + bw * 0.5f;
        float y2 = cy + bh * 0.5f;
        
        // Scale to original image size
        float gain_x = (float)W / (float)m_inputWidth;
        float gain_y = (float)H / (float)m_inputHeight;
        x1 *= gain_x; x2 *= gain_x;
        y1 *= gain_y; y2 *= gain_y;
        
        // Clamp to image bounds
        x1 = std::min(std::max(x1, 0.0f), float(W - 1));
        y1 = std::min(std::max(y1, 0.0f), float(H - 1));
        x2 = std::min(std::max(x2, 0.0f), float(W - 1));
        y2 = std::min(std::max(y2, 0.0f), float(H - 1));
        
        int rw = int(std::max(0.0f, x2 - x1));
        int rh = int(std::max(0.0f, y2 - y1));
        if (rw <= 0 || rh <= 0) continue;
        
        proposals.push_back(Det{cv::Rect((int)x1, (int)y1, rw, rh), best_cls, best_p});
    }
    
    // Apply NMS
    final_dets = nms(proposals, IOU_THRESHOLD);
    
    return final_dets;
}
 
bool ProviderSensor::Initialize()
{
    m_logger.LogVerbose() << "ProviderSensor::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<providersensor::rootswcomponent::port::Sensor>();
    m_Sensorv2 = std::make_unique<providersensor::rootswcomponent::port::Sensorv2>();
    
    // Initialize TFLite model
    if (!InitializeTFLite()) {
        m_logger.LogError() << "Failed to initialize TFLite model!";
        init = false;
    }
    
    return init;
}
 
void ProviderSensor::Start()
{
    m_logger.LogVerbose() << "ProviderSensor::Start";
    
    // m_Sensor->Start();  // Disabled normal sensor
    m_Sensorv2->Start();
}
 
void ProviderSensor::Terminate()
{
    m_logger.LogVerbose() << "ProviderSensor::Terminate";
    
    // stop running
    m_running = false;
    
    // m_Sensor->Terminate();  // Disabled normal sensor
    m_Sensorv2->Terminate();
}
 
void ProviderSensor::Run()
{
    m_logger.LogVerbose() << "ProviderSensor::Run";
    
    // start running
    m_running = true;

    // Camera capture and YOLOv11 inference loop
    m_workers.Async(
        [this] {
            // 1. INITIALIZE CAMERA
            cv::VideoCapture cap(0);
            
            // Set resolution
            cap.set(cv::CAP_PROP_FRAME_WIDTH, 640);
            cap.set(cv::CAP_PROP_FRAME_HEIGHT, 640);

            if (!cap.isOpened()) {
                m_logger.LogError() << "ERROR: Could not open camera!";
            } else {
                m_logger.LogInfo() << "Camera opened successfully";
            }

            ara::sensor::SensorVectorType m_sensorData;
            cv::Mat frame;

            // Main application loop
            while (m_running) {
                auto t_total_start = std::chrono::high_resolution_clock::now();
                
                // 2. CAPTURE FRAME
                bool ret = cap.read(frame);

                if (!ret || frame.empty()) {
                    m_logger.LogError() << "Failed to grab frame from camera! Sending dummy data...";
                    m_sensorData.assign(2000, 0);
                }
                else {
                    // 3. RUN YOLO INFERENCE
                    auto t_inf_start = std::chrono::high_resolution_clock::now();
                    std::vector<Det> detections = ProcessFrame(frame);
                    auto t_inf_end = std::chrono::high_resolution_clock::now();
                    std::chrono::duration<double, std::milli> t_inf_ms = t_inf_end - t_inf_start;
                    
                    m_logger.LogInfo() << "Inference time: " << t_inf_ms.count() << " ms, Detections: " << detections.size();
                    
                    // 4. DRAW DETECTIONS ON FRAME
                    for (const auto& d : detections) {
                        cv::rectangle(frame, d.rect, cv::Scalar(0, 255, 0), 2);
                        
                        char text[128];
                        std::snprintf(text, sizeof(text), "%s %.2f",
                                      (d.cls >= 0 && d.cls < 6) ? CLASS_NAMES[d.cls] : "cls?",
                                      d.score);
                        
                        int baseline = 0;
                        cv::Size ts = cv::getTextSize(text, cv::FONT_HERSHEY_SIMPLEX, 0.6, 2, &baseline);
                        int x1 = d.rect.x;
                        int y1 = std::max(0, d.rect.y - ts.height - 6);
                        
                        cv::rectangle(frame,
                                      cv::Point(x1, y1),
                                      cv::Point(x1 + ts.width + 6, y1 + ts.height + 6),
                                      cv::Scalar(0, 255, 0), cv::FILLED);
                        cv::putText(frame, text,
                                    cv::Point(x1 + 3, y1 + ts.height + 1),
                                    cv::FONT_HERSHEY_SIMPLEX, 0.6,
                                    cv::Scalar(0, 0, 0), 2);
                        
                        // Log each detection
                        m_logger.LogInfo() << "Detected: " << CLASS_NAMES[d.cls] 
                                           << " conf=" << d.score
                                           << " box=[" << d.rect.x << "," << d.rect.y 
                                           << "," << d.rect.width << "," << d.rect.height << "]";
                    }
                    
                    // 5. ENCODE ANNOTATED IMAGE
                    std::vector<uchar> buf;
                    std::vector<int> params = {cv::IMWRITE_JPEG_QUALITY, 100};
                    cv::imencode(".jpg", frame, buf, params);
                    
                    m_sensorData.assign(buf.begin(), buf.end());
                    
                    auto t_total_end = std::chrono::high_resolution_clock::now();
                    std::chrono::duration<double, std::milli> t_total_ms = t_total_end - t_total_start;
                    
                    m_logger.LogInfo() << "Frame processed. Size: " << m_sensorData.size() 
                                       << " bytes, Total time: " << t_total_ms.count() << " ms";
                }

                // 6. TRANSMIT DATA
                m_Sensorv2->SendEventEvent_RequestDataTriggered(m_sensorData);
                
                m_sensorData.clear();
                
                // 7. CONTROL FRAME RATE (~40 FPS)
                std::this_thread::sleep_for(std::chrono::milliseconds(25));
            }
            
            cap.release();
        }
    );
    
    m_workers.Wait();
}
 
} /// namespace rootswcomponent
} /// namespace providersensor
