///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.h
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/rootswcomponent/port/sensor.h"
#include "providersensor/rootswcomponent/port/sensorv2.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"

#include <opencv2/opencv.hpp>
#include <vector>
#include <array>
#include <memory>

// TFLite headers
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/c/common.h"

namespace providersensor
{
namespace rootswcomponent
{

/// @brief Detection result structure
struct Det {
    cv::Rect rect;
    int cls;
    float score;
};

class ProviderSensor
{
public:
    /// @brief Constructor
    ProviderSensor();
    
    /// @brief Destructor
    ~ProviderSensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Calculate IoU between two rectangles
    static float IoU(const cv::Rect& a, const cv::Rect& b);
    
    /// @brief Non-Maximum Suppression
    static std::vector<Det> nms(const std::vector<Det>& dets, float iou_thr);
    
    /// @brief Initialize TFLite model
    bool InitializeTFLite();
    
    /// @brief Process frame with YOLOv11 model
    std::vector<Det> ProcessFrame(const cv::Mat& frame);

    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {ProviderSensor.Sensor}
    std::unique_ptr<providersensor::rootswcomponent::port::Sensor> m_Sensor;
    
    /// @brief Instance of Port {ProviderSensor.Sensorv2}
    std::unique_ptr<providersensor::rootswcomponent::port::Sensorv2> m_Sensorv2;

    /// @brief TFLite model
    std::unique_ptr<tflite::FlatBufferModel> m_model;
    
    /// @brief TFLite interpreter
    std::unique_ptr<tflite::Interpreter> m_interpreter;
    
    /// @brief Model input dimensions
    int m_inputHeight;
    int m_inputWidth;
    int m_inputChannels;
    
    /// @brief Model output dimensions
    int m_numClasses;
    int m_numDetections;
    
    /// @brief Detection thresholds
    static constexpr float CONF_THRESHOLD = 0.25f;
    static constexpr float IOU_THRESHOLD = 0.45f;
    
    /// @brief Class names for traffic light detection
    static const char* CLASS_NAMES[6];
};
 
} /// namespace rootswcomponent
} /// namespace providersensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H