///////////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.
///
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.h
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/aa/port/pport0.h"

#include "ara/log/logger.h"
#include "para/swc/port_pool.h"

#include <opencv2/opencv.hpp>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <memory>
#include <numeric>
#include <string>
#include <sstream>
#include <thread>
#include <vector>
#include <stdexcept>

// POSIX / UART headers
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <cerrno>
#include <sys/select.h>

// TFLite headers
#include "tensorflow/lite/core/c/common.h"
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/interpreter_builder.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model_builder.h"

// GPS / map headers
#include "traffic_node.h"
#include "geojson_parser.h"
#include "kdtree.h"

namespace providersensor
{
namespace aa
{

// ─────────────────────────── PIPELINE STRUCTS ──────────────────────────────

struct Box {
    float x1, y1, x2, y2, conf;
    int   cls;

    float cx()   const { return (x1 + x2) * 0.5f; }
    float cy()   const { return (y1 + y2) * 0.5f; }
    float area() const { return std::max(0.f,x2-x1) * std::max(0.f,y2-y1); }

    float distTo(const Box& o) const {
        float dx=cx()-o.cx(), dy=cy()-o.cy();
        return std::sqrt(dx*dx + dy*dy);
    }

    cv::Rect toRect() const {
        int x=static_cast<int>(x1), y=static_cast<int>(y1);
        int w=static_cast<int>(x2-x1), h=static_cast<int>(y2-y1);
        return {x, y, std::max(1,w), std::max(1,h)};
    }
};

struct LbInfo {
    float scale;
    int   pad_top, pad_left;
    int   orig_w, orig_h;
    int   target;
};

struct DirResult {
    const char* name      = nullptr;
    Box         dir_orig  {};
    Box         timer_orig{};
    bool        has_timer = false;
    std::string color;
    std::string timer_val;
};

// Full definition lives in providersensor.cpp (pimpl pattern)
class YoloDetector;

// ─────────────────────────── PROVIDER SENSOR ───────────────────────────────

class ProviderSensor
{
public:
    ProviderSensor();
    ~ProviderSensor();

    bool Initialize();
    void Start();
    void Terminate();
    void Run();

private:
    bool m_running;
    ::para::swc::PortPool m_workers;
    ara::log::Logger& m_logger;
    std::unique_ptr<providersensor::aa::port::PPort0> m_PPort0;

    std::unique_ptr<YoloDetector>            m_yolo;
    std::unique_ptr<tflite::FlatBufferModel> m_timerModel;
    std::unique_ptr<KDTree>                  m_kdTree;

    bool    InitializeModels();
    // outWidth>0: annotate on a resized copy (boxes scaled to match); 0=full resolution
    cv::Mat processFrame(const cv::Mat& frame, std::string& out_color, int outWidth = 0);

    static cv::Mat            letterbox(const cv::Mat& img, int target, LbInfo& lb);
    static Box                inverseMap(const Box& b, const LbInfo& lb);
    static std::string        detectColor(const cv::Mat& roi_bgr);
    static std::vector<float> dequantizePerTensor(const TfLiteTensor* t);
    static std::string        decodeOcr(const float* L, const float* S1,
                                         const float* S2, const float* S3);
    static std::string        runOcr(const cv::Mat& roi_bgr,
                                      const tflite::FlatBufferModel* model,
                                      ara::log::Logger& logger);
    static void               dirWorker(DirResult& res, const cv::Mat& orig,
                                         const std::vector<Box>& timers_orig,
                                         const tflite::FlatBufferModel* timerModel,
                                         ara::log::Logger& logger);
    static cv::Scalar         colorOf(const std::string& c);
    static void               drawBox(cv::Mat& img, const Box& b,
                                       const cv::Scalar& col, const std::string& label);

    // ── GPS seqlock handoff (GPS thread writes, camera thread reads) ───────
    struct GpsSnapshot {
        std::int64_t nodeId{0};
        std::int32_t distM{0};
        std::uint8_t inRange{0};
    };
    void publishGpsSnapshot(std::int64_t nodeId, std::int32_t distM, std::uint8_t inRange);
    bool tryCopyGpsSnapshot(GpsSnapshot& out) const;

    mutable std::atomic<std::uint32_t> m_gpsSeq{0};
    alignas(64) GpsSnapshot m_gpsSnapshot{};

    std::string m_last_detected_color{"unknown"};
    int         m_consecutive_color_count{0};
    std::string m_stable_traffic_color{"unknown"};

    // ── GPS UART helpers ──────────────────────────────────────────────────
    static double                   nmeaToDeg(const std::string& field, char hemi);
    static std::vector<std::string> splitNmea(const std::string& line);
    static bool                     parseNmeaFix(const std::string& raw, Coordinates& out);
    static int                      openGPSUART();
    static bool                     readNextGPSFix(int fd, Coordinates& fix);
};

} // namespace aa
} // namespace providersensor

#endif // PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H
