///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : clientsensor.cpp
/// SOFTWARE COMPONENT NAME           : ClientSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/aa/clientsensor.h"
 
namespace clientsensor
{
namespace aa
{
 
ClientSensor::ClientSensor()
    : m_logger(ara::log::CreateLogger("cSen", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
{
}
 
ClientSensor::~ClientSensor()
{
}
 
bool ClientSensor::Initialize()
{
    m_logger.LogVerbose() << "ClientSensor::Initialize";
    
    bool init = true;
    
    m_RPort0 = std::make_unique<clientsensor::aa::port::RPort0>();
    
    // put your code for initialization
    m_RPort0->RegistEventHandlerimageDataEvent([this](const sensorCam::proxy::events::imageDataEvent::SampleType& data) {
        // handle received data
        if (data.empty()) return;

        m_logger.LogInfo() << "Received data size: " << data.size();

        try {
            // 1. Decode byte data to OpenCV image
            cv::Mat img = cv::imdecode(data, cv::IMREAD_COLOR);

            if (!img.empty()) {
                // 2. Write image to file
                std::string filename = "received_output.jpg";
                if (cv::imwrite(filename, img)) {
                    m_logger.LogInfo() << "Image saved to " << filename.c_str();
                } else {
                    m_logger.LogError() << "Failed to save image file";
                }
            } else {
                m_logger.LogError() << "Failed to decode image";
            }
        } catch (const cv::Exception& e) {
            m_logger.LogError() << "OpenCV Exception: " << e.what();
        }
    });
    
    return init;
}
 
void ClientSensor::Start()
{
    m_logger.LogVerbose() << "ClientSensor::Start";
    
    m_RPort0->Start();
}
 
void ClientSensor::Terminate()
{
    m_logger.LogVerbose() << "ClientSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_RPort0->Terminate();
}
 
void ClientSensor::Run()
{
    m_logger.LogVerbose() << "ClientSensor::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_RPort0->ReceiveEventimageDataEventCyclic(); });
    
    // m_workers.Wait();

    while (m_running)
    {
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
} /// namespace aa
} /// namespace clientsensor
