///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.h
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2025-11-22 09:36:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/rootswcomponent/port/sensor.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"
 
namespace providersensor
{
namespace rootswcomponent
{
 
class ProviderSensor
{
public:
    /// @brief Constructor
    ProviderSensor();
    
    /// @brief Destructor
    ~ProviderSensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {ProviderSensor.Sensor}
    std::unique_ptr<providersensor::rootswcomponent::port::Sensor> m_Sensor;
    
    /// @brief Example sensor data to be sent
    ara::sensor::SensorVectorType m_sensorData;
};
 
} /// namespace rootswcomponent
} /// namespace providersensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_ROOTSWCOMPONENT_H