///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : providersensor.h
/// SOFTWARE COMPONENT NAME           : ProviderSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "providersensor/aa/port/pport0.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"

#include <opencv2/opencv.hpp>
#include <vector>
#include <array>
#include <memory>
#include <string>
#include <sstream>
#include <thread>
#include <chrono>
#include <stdexcept>
#include <atomic>
#include <cstdint>

// POSIX / UART headers
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <cerrno>
#include <cstring>
#include <sys/select.h>

// TFLite headers
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/c/common.h"

// GPS / map headers
#include "traffic_node.h"
#include "geojson_parser.h"
#include "kdtree.h"

// Define constants for GPS and map handling




namespace providersensor
{
namespace aa
{

/// @brief Detection result structure
struct Det {
    cv::Rect rect;
    int cls;
    float score;
};
 
class ProviderSensor
{
public:
    /// @brief Constructor
    ProviderSensor();
    
    /// @brief Destructor
    ~ProviderSensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {ProviderSensor.PPort0}
    std::unique_ptr<providersensor::aa::port::PPort0> m_PPort0;

    ///////////////////////////My Code///////////////////////////

    /// @brief Calculate IoU between two rectangles
    static float IoU(const cv::Rect& a, const cv::Rect& b);
    
    /// @brief Non-Maximum Suppression
    static std::vector<Det> nms(const std::vector<Det>& dets, float iou_thr);
    
    /// @brief Initialize TFLite model
    bool InitializeTFLite();
    
    /// @brief Process frame with YOLOv11 model
    std::vector<Det> ProcessFrame(const cv::Mat& frame);

    /// @brief TFLite model
    std::unique_ptr<tflite::FlatBufferModel> m_model;
    
    /// @brief TFLite interpreter
    std::unique_ptr<tflite::Interpreter> m_interpreter;
    
    /// @brief Model input dimensions
    int m_inputHeight;
    int m_inputWidth;
    int m_inputChannels;
    
    /// @brief Model output dimensions
    int m_numClasses;
    int m_numDetections;
    
    /// @brief Detection thresholds
    static constexpr float CONF_THRESHOLD = 0.25f;
    static constexpr float IOU_THRESHOLD = 0.45f;
    
    /// @brief Class names for traffic light detection
    static const char* CLASS_NAMES[];
    static const int CLASS_NAMES_SIZE;

    /// @brief NMEA helpers
    static double nmeaToDeg(const std::string& field, char hemi); 
    static std::vector<std::string> splitNmea(const std::string& line);
    static bool parseNmeaFix(const std::string& raw, Coordinates& out); 

    /// @brief UART open
    static int openGPSUART();
    static bool readNextGPSFix(int fd, Coordinates& fix);

    /// Lock-free handoff: GPS thread writes, camera thread reads (seqlock, no mutex).
    struct GpsSnapshot
    {
        std::int64_t nodeId{0};
        std::int32_t distM{0};
        std::uint8_t inRange{0};
    };
    void publishGpsSnapshot(std::int64_t nodeId, std::int32_t distM, std::uint8_t inRange);
    bool tryCopyGpsSnapshot(GpsSnapshot& out) const;

    // Sequence counter: 0 for unlocked, 1 for locked
    mutable std::atomic<std::uint32_t> m_gpsSeq{0};
    // GPS_Snapshot variable: atomic copy of the GPS snapshot
    alignas(64) GpsSnapshot m_gpsSnapshot{};

};
 
} /// namespace aa
} /// namespace providersensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PROVIDERSENSOR_AA_H