///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusion.cpp
/// SOFTWARE COMPONENT NAME           : Fusion
/// GENERATED DATE                    : 2025-10-20 13:08:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "fusion/aa/fusion.h"
 
namespace fusion
{
namespace aa
{
 
Fusion::Fusion()
    : m_logger(ara::log::CreateLogger("FUSI", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(1)
{
}
 
Fusion::~Fusion()
{
}
 
bool Fusion::Initialize()
{
    m_logger.LogVerbose() << "Fusion::Initialize";
    
    bool init = true;
    
    m_Sensor = std::make_unique<fusion::aa::port::Sensor>();
    
    // put your code for initialization

    m_Sensor->RegistEventHandlerSensorData(
        [this](const sensor::service::proxy::events::SensorData::SampleType& data)
        {
            m_logger.LogVerbose() << "[Fusion] SensorData Humidity via polling = " << data;
        });
    
    return init;
}
 
void Fusion::Start()
{
    m_logger.LogVerbose() << "Fusion::Start";
    
    m_Sensor->Start();
}
 
void Fusion::Terminate()
{
    m_logger.LogVerbose() << "Fusion::Terminate";
    
    // stop running
    m_running = false;
    
    m_Sensor->Terminate();
}
 
void Fusion::Run()
{
    m_logger.LogVerbose() << "Fusion::Run";
    
    // start running
    m_running = true;
    
    m_workers.Async([this] { m_Sensor->ReceiveEventSensorDataCyclic(); });
    
    m_workers.Wait();
}
 
} /// namespace aa
} /// namespace fusion
