///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : clientsensor.cpp
/// SOFTWARE COMPONENT NAME           : ClientSensor
/// GENERATED DATE                    : 2026-03-05 23:25:53
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "clientsensor/aa/clientsensor.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <iostream>
#include <cstring>
#include <cstdint>
#include <vector>

namespace
{
constexpr std::uint32_t kGpsJpegMagic = 0x47505331u;

static bool sendAll(int s, const void* buf, std::size_t len)
{
    const char* p = static_cast<const char*>(buf);
    std::size_t off = 0;
    while (off < len)
    {
        ssize_t n = send(s, p + off, len - off, MSG_NOSIGNAL);
        if (n <= 0)
        {
            return false;
        }
        off += static_cast<std::size_t>(n);
    }
    return true;
}

/// Parsed GPS-JPEG wire from ProviderSensor; on legacy raw JPEG, returns inRange=0 and full buffer as JPEG.
static void parseImageData(const sensorCam::proxy::events::imageDataEvent::SampleType& data, std::vector<std::uint8_t>& jpegOut,
                          std::uint8_t& inRange, std::int64_t& nodeId, std::int32_t& distM)
{
    inRange = 0;
    nodeId = 0;
    distM = 0;
    if (data.size() < 24)
    {
        jpegOut.assign(reinterpret_cast<const std::uint8_t*>(data.data()),
                       reinterpret_cast<const std::uint8_t*>(data.data()) + data.size());
        return;
    }
    std::uint32_t mag = 0;
    std::memcpy(&mag, data.data(), 4);
    if (mag != kGpsJpegMagic)
    {
        jpegOut.assign(reinterpret_cast<const std::uint8_t*>(data.data()),
                       reinterpret_cast<const std::uint8_t*>(data.data()) + data.size());
        return;
    }
    std::uint32_t jlen = 0;
    std::memcpy(&jlen, data.data() + 20, 4);
    if (jlen == 0U || 24U + jlen != static_cast<std::uint32_t>(data.size()))
    {
        jpegOut.assign(reinterpret_cast<const std::uint8_t*>(data.data()),
                       reinterpret_cast<const std::uint8_t*>(data.data()) + data.size());
        return;
    }
    std::memcpy(&inRange, data.data() + 5, 1);
    std::memcpy(&nodeId, data.data() + 8, 8);
    std::memcpy(&distM, data.data() + 16, 4);
    jpegOut.resize(jlen);
    std::memcpy(jpegOut.data(), data.data() + 24, jlen);
}
} /// namespace

namespace clientsensor
{
namespace aa
{

ClientSensor::ClientSensor()
    : m_logger(ara::log::CreateLogger("cSen", "SWC", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_workers(2)
{
}

ClientSensor::~ClientSensor()
{
}

bool ClientSensor::Initialize()
{
    m_logger.LogVerbose() << "ClientSensor::Initialize";
    
    // Tạo Cấu trúc tĩnh trong hàm để giữ Connection
    static int sock = -1;
    static struct sockaddr_in server_addr;

    // Hàm Lambda tự động gọi nếu Socket mất kết nối
    auto ConnectTCP = [&]() {
        if (sock >= 0) close(sock);
        sock = socket(AF_INET, SOCK_STREAM, 0);
        if (sock < 0) return;
        
        server_addr.sin_family = AF_INET;
        server_addr.sin_port = htons(8888);
        
        // Try Docker host gateway IP first (for when show_cam.py runs outside docker)
        server_addr.sin_addr.s_addr = inet_addr("172.31.0.1");
        if (connect(sock, (struct sockaddr*)&server_addr, sizeof(server_addr)) < 0) {
            // Fallback to localhost (for native / non-docker execution)
            server_addr.sin_addr.s_addr = inet_addr("127.0.0.1");
            if (connect(sock, (struct sockaddr*)&server_addr, sizeof(server_addr)) < 0) {
                close(sock);
                sock = -1;
            }
        }
    };

    // Gọi lần đầu lúc khởi động ứng dụng
    ConnectTCP();

    bool init = true;
    m_RPort0 = std::make_unique<clientsensor::aa::port::RPort0>();
    
    m_RPort0->RegistEventHandlerimageDataEvent([ConnectTCP, this](const sensorCam::proxy::events::imageDataEvent::SampleType& data) {
        if (data.empty()) return;

        // Nếu TCP bị đứt hoặc chưa khởi động Python, cố connect lại ngay trước khi ném dữ liệu
        if (sock < 0) {
            ConnectTCP();
        }

        if (sock >= 0) {
            std::vector<std::uint8_t> jpeg;
            std::uint8_t inRange = 0;
            std::int64_t nodeId = 0;
            std::int32_t distM = 0;
            parseImageData(data, jpeg, inRange, nodeId, distM);

            const std::uint32_t jlen = static_cast<std::uint32_t>(jpeg.size());
            const bool ok = sendAll(sock, &jlen, sizeof(jlen)) && (jlen == 0U || sendAll(sock, jpeg.data(), jpeg.size()))
                && sendAll(sock, &inRange, 1) && sendAll(sock, &nodeId, 8) && sendAll(sock, &distM, 4);
            if (!ok)
            {
                close(sock);
                sock = -1;
            }
        }
    });
    
    return init;
}
 
void ClientSensor::Start()
{
    m_logger.LogVerbose() << "ClientSensor::Start";
    
    m_RPort0->Start();
}
 
void ClientSensor::Terminate()
{
    m_logger.LogVerbose() << "ClientSensor::Terminate";
    
    // stop running
    m_running = false;
    
    m_RPort0->Terminate();
}
 
void ClientSensor::Run()
{
    m_logger.LogVerbose() << "ClientSensor::Run";
    
    // start running
    m_running = true;
    
    // m_workers.Async([this] { m_RPort0->ReceiveEventimageDataEventCyclic(); });
    
    // m_workers.Wait();

    while (m_running)
    {
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
} /// namespace aa
} /// namespace clientsensor
