///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_sensorvectortype.h
/// IMPLEMENTATION DATA TYPE NAME     : SensorVectorType
/// GENERATED DATE                    : 2025-11-24 18:44:15
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_ARA_SENSOR_CPP_IMPL_TYPE_SENSORVECTORTYPE_H
#define PARA_ARA_COM_GEN_ARA_SENSOR_CPP_IMPL_TYPE_SENSORVECTORTYPE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/vector.h>
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_sensorvectortype.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace ara
{
namespace sensor
{
using SensorVectorType = ara::core::Vector<std::uint8_t>;
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::ara::sensor::SensorVectorType SensorVectorType_ConvertToDdsType(const ara::sensor::SensorVectorType& src)
{
    return src;
}
 
inline ara::sensor::SensorVectorType SensorVectorType_ConvertFromDdsType(const dds::ara::sensor::SensorVectorType& src)
{
    return src;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace sensor
} /// namespace ara
#endif /// PARA_ARA_COM_GEN_ARA_SENSOR_CPP_IMPL_TYPE_SENSORVECTORTYPE_H